# golangci-lint configuration
# Note: Some editors (like Zed) may show YAML validation errors, but this file
# is valid for golangci-lint. Run `golangci-lint run` to verify.

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - gosec
    - unconvert
    - goconst
    - gocyclo

issues:
  exclude-rules:
    # Ignore struct tag warnings for participle grammar in parser
    - path: internal/parser/parser.go
      linters:
        - govet
      text: "struct field tag.*not compatible with reflect.StructTag.Get"

    # Allow file reading in parser (CLI tool reads user-specified files)
    - path: internal/parser/parser.go
      linters:
        - gosec
      text: "G304.*Potential file inclusion via variable"

    # Allow high complexity in binder - handles many DSL node types
    - path: internal/parser/binder.go
      linters:
        - gocyclo
      text: "cyclomatic complexity.*of func `Bind`"

    # Allow high complexity in serializer - handles many model types
    - path: internal/parser/serializer.go
      linters:
        - gocyclo
      text: "cyclomatic complexity.*of func `serializeCase`"

  exclude-use-default: false

linters-settings:
  gocyclo:
    min-complexity: 20

  gosec:
    excludes:
      - G104 # Ignore unhandled errors in some contexts
