// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto_shared/data_service.proto

package kycdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------
// Messages - Attributes
// ----------------------
type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AttrType      string                 `protobuf:"bytes,4,opt,name=attr_type,json=attrType,proto3" json:"attr_type,omitempty"`
	Jurisdiction  string                 `protobuf:"bytes,5,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Regulation    string                 `protobuf:"bytes,6,opt,name=regulation,proto3" json:"regulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_proto_shared_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Attribute) GetAttrType() string {
	if x != nil {
		return x.AttrType
	}
	return ""
}

func (x *Attribute) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *Attribute) GetRegulation() string {
	if x != nil {
		return x.Regulation
	}
	return ""
}

type GetAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeRequest) Reset() {
	*x = GetAttributeRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeRequest) ProtoMessage() {}

func (x *GetAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAttributesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAttributesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AttributeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeList) Reset() {
	*x = AttributeList{}
	mi := &file_proto_shared_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeList) ProtoMessage() {}

func (x *AttributeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeList.ProtoReflect.Descriptor instead.
func (*AttributeList) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *AttributeList) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AttributeList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ----------------------
// Messages - Documents
// ----------------------
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Jurisdiction  string                 `protobuf:"bytes,3,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_shared_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *Document) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Jurisdiction  string                 `protobuf:"bytes,3,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDocumentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDocumentsRequest) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

type DocumentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentList) Reset() {
	*x = DocumentList{}
	mi := &file_proto_shared_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentList) ProtoMessage() {}

func (x *DocumentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentList.ProtoReflect.Descriptor instead.
func (*DocumentList) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentList) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *DocumentList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ----------------------
// Messages - Cases
// ----------------------
type CaseVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseId        string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	DslSource     string                 `protobuf:"bytes,3,opt,name=dsl_source,json=dslSource,proto3" json:"dsl_source,omitempty"`
	CompiledJson  string                 `protobuf:"bytes,4,opt,name=compiled_json,json=compiledJson,proto3" json:"compiled_json,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseVersion) Reset() {
	*x = CaseVersion{}
	mi := &file_proto_shared_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseVersion) ProtoMessage() {}

func (x *CaseVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseVersion.ProtoReflect.Descriptor instead.
func (*CaseVersion) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *CaseVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaseVersion) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CaseVersion) GetDslSource() string {
	if x != nil {
		return x.DslSource
	}
	return ""
}

func (x *CaseVersion) GetCompiledJson() string {
	if x != nil {
		return x.CompiledJson
	}
	return ""
}

func (x *CaseVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaseVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CaseVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	DslSource     string                 `protobuf:"bytes,2,opt,name=dsl_source,json=dslSource,proto3" json:"dsl_source,omitempty"`
	CompiledJson  string                 `protobuf:"bytes,3,opt,name=compiled_json,json=compiledJson,proto3" json:"compiled_json,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseVersionRequest) Reset() {
	*x = CaseVersionRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseVersionRequest) ProtoMessage() {}

func (x *CaseVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseVersionRequest.ProtoReflect.Descriptor instead.
func (*CaseVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *CaseVersionRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CaseVersionRequest) GetDslSource() string {
	if x != nil {
		return x.DslSource
	}
	return ""
}

func (x *CaseVersionRequest) GetCompiledJson() string {
	if x != nil {
		return x.CompiledJson
	}
	return ""
}

func (x *CaseVersionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CaseVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseVersionResponse) Reset() {
	*x = CaseVersionResponse{}
	mi := &file_proto_shared_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseVersionResponse) ProtoMessage() {}

func (x *CaseVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseVersionResponse.ProtoReflect.Descriptor instead.
func (*CaseVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{10}
}

func (x *CaseVersionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CaseVersionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CaseVersionResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseRequest) Reset() {
	*x = GetCaseRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseRequest) ProtoMessage() {}

func (x *GetCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseRequest.ProtoReflect.Descriptor instead.
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type ListCaseVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaseVersionsRequest) Reset() {
	*x = ListCaseVersionsRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaseVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaseVersionsRequest) ProtoMessage() {}

func (x *ListCaseVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaseVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListCaseVersionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListCaseVersionsRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ListCaseVersionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCaseVersionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CaseVersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*CaseVersion         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseVersionList) Reset() {
	*x = CaseVersionList{}
	mi := &file_proto_shared_data_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseVersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseVersionList) ProtoMessage() {}

func (x *CaseVersionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseVersionList.ProtoReflect.Descriptor instead.
func (*CaseVersionList) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{13}
}

func (x *CaseVersionList) GetVersions() []*CaseVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *CaseVersionList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListAllCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // Optional filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllCasesRequest) Reset() {
	*x = ListAllCasesRequest{}
	mi := &file_proto_shared_data_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllCasesRequest) ProtoMessage() {}

func (x *ListAllCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllCasesRequest.ProtoReflect.Descriptor instead.
func (*ListAllCasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListAllCasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAllCasesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAllCasesRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type CaseSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	VersionCount  int32                  `protobuf:"varint,2,opt,name=version_count,json=versionCount,proto3" json:"version_count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseSummary) Reset() {
	*x = CaseSummary{}
	mi := &file_proto_shared_data_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseSummary) ProtoMessage() {}

func (x *CaseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseSummary.ProtoReflect.Descriptor instead.
func (*CaseSummary) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{15}
}

func (x *CaseSummary) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CaseSummary) GetVersionCount() int32 {
	if x != nil {
		return x.VersionCount
	}
	return 0
}

func (x *CaseSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaseSummary) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type CaseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cases         []*CaseSummary         `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseList) Reset() {
	*x = CaseList{}
	mi := &file_proto_shared_data_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseList) ProtoMessage() {}

func (x *CaseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_data_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseList.ProtoReflect.Descriptor instead.
func (*CaseList) Descriptor() ([]byte, []int) {
	return file_proto_shared_data_service_proto_rawDescGZIP(), []int{16}
}

func (x *CaseList) GetCases() []*CaseSummary {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *CaseList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_proto_shared_data_service_proto protoreflect.FileDescriptor

const file_proto_shared_data_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto_shared/data_service.proto\x12\bkyc.data\"\xb2\x01\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tattr_type\x18\x04 \x01(\tR\battrType\x12\"\n" +
	"\fjurisdiction\x18\x05 \x01(\tR\fjurisdiction\x12\x1e\n" +
	"\n" +
	"regulation\x18\x06 \x01(\tR\n" +
	"regulation\"%\n" +
	"\x13GetAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x15ListAttributesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"e\n" +
	"\rAttributeList\x123\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x13.kyc.data.AttributeR\n" +
	"attributes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa4\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\"\n" +
	"\fjurisdiction\x18\x03 \x01(\tR\fjurisdiction\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x14ListDocumentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\"\n" +
	"\fjurisdiction\x18\x03 \x01(\tR\fjurisdiction\"a\n" +
	"\fDocumentList\x120\n" +
	"\tdocuments\x18\x01 \x03(\v2\x12.kyc.data.DocumentR\tdocuments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb1\x01\n" +
	"\vCaseVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x1d\n" +
	"\n" +
	"dsl_source\x18\x03 \x01(\tR\tdslSource\x12#\n" +
	"\rcompiled_json\x18\x04 \x01(\tR\fcompiledJson\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x89\x01\n" +
	"\x12CaseVersionRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x1d\n" +
	"\n" +
	"dsl_source\x18\x02 \x01(\tR\tdslSource\x12#\n" +
	"\rcompiled_json\x18\x03 \x01(\tR\fcompiledJson\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"d\n" +
	"\x13CaseVersionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\")\n" +
	"\x0eGetCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"`\n" +
	"\x17ListCaseVersionsRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"e\n" +
	"\x0fCaseVersionList\x121\n" +
	"\bversions\x18\x01 \x03(\v2\x15.kyc.data.CaseVersionR\bversions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"h\n" +
	"\x13ListAllCasesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"\x86\x01\n" +
	"\vCaseSummary\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12#\n" +
	"\rversion_count\x18\x02 \x01(\x05R\fversionCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\flast_updated\x18\x04 \x01(\tR\vlastUpdated\"X\n" +
	"\bCaseList\x12+\n" +
	"\x05cases\x18\x01 \x03(\v2\x15.kyc.data.CaseSummaryR\x05cases\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xad\x02\n" +
	"\x11DictionaryService\x12B\n" +
	"\fGetAttribute\x12\x1d.kyc.data.GetAttributeRequest\x1a\x13.kyc.data.Attribute\x12J\n" +
	"\x0eListAttributes\x12\x1f.kyc.data.ListAttributesRequest\x1a\x17.kyc.data.AttributeList\x12?\n" +
	"\vGetDocument\x12\x1c.kyc.data.GetDocumentRequest\x1a\x12.kyc.data.Document\x12G\n" +
	"\rListDocuments\x12\x1e.kyc.data.ListDocumentsRequest\x1a\x16.kyc.data.DocumentList2\xb5\x02\n" +
	"\vCaseService\x12N\n" +
	"\x0fSaveCaseVersion\x12\x1c.kyc.data.CaseVersionRequest\x1a\x1d.kyc.data.CaseVersionResponse\x12A\n" +
	"\x0eGetCaseVersion\x12\x18.kyc.data.GetCaseRequest\x1a\x15.kyc.data.CaseVersion\x12P\n" +
	"\x10ListCaseVersions\x12!.kyc.data.ListCaseVersionsRequest\x1a\x19.kyc.data.CaseVersionList\x12A\n" +
	"\fListAllCases\x12\x1d.kyc.data.ListAllCasesRequest\x1a\x12.kyc.data.CaseListB/P\x01Z+github.com/adamtc007/KYC-DSL/api/pb/kycdatab\x06proto3"

var (
	file_proto_shared_data_service_proto_rawDescOnce sync.Once
	file_proto_shared_data_service_proto_rawDescData []byte
)

func file_proto_shared_data_service_proto_rawDescGZIP() []byte {
	file_proto_shared_data_service_proto_rawDescOnce.Do(func() {
		file_proto_shared_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shared_data_service_proto_rawDesc), len(file_proto_shared_data_service_proto_rawDesc)))
	})
	return file_proto_shared_data_service_proto_rawDescData
}

var file_proto_shared_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shared_data_service_proto_goTypes = []any{
	(*Attribute)(nil),               // 0: kyc.data.Attribute
	(*GetAttributeRequest)(nil),     // 1: kyc.data.GetAttributeRequest
	(*ListAttributesRequest)(nil),   // 2: kyc.data.ListAttributesRequest
	(*AttributeList)(nil),           // 3: kyc.data.AttributeList
	(*Document)(nil),                // 4: kyc.data.Document
	(*GetDocumentRequest)(nil),      // 5: kyc.data.GetDocumentRequest
	(*ListDocumentsRequest)(nil),    // 6: kyc.data.ListDocumentsRequest
	(*DocumentList)(nil),            // 7: kyc.data.DocumentList
	(*CaseVersion)(nil),             // 8: kyc.data.CaseVersion
	(*CaseVersionRequest)(nil),      // 9: kyc.data.CaseVersionRequest
	(*CaseVersionResponse)(nil),     // 10: kyc.data.CaseVersionResponse
	(*GetCaseRequest)(nil),          // 11: kyc.data.GetCaseRequest
	(*ListCaseVersionsRequest)(nil), // 12: kyc.data.ListCaseVersionsRequest
	(*CaseVersionList)(nil),         // 13: kyc.data.CaseVersionList
	(*ListAllCasesRequest)(nil),     // 14: kyc.data.ListAllCasesRequest
	(*CaseSummary)(nil),             // 15: kyc.data.CaseSummary
	(*CaseList)(nil),                // 16: kyc.data.CaseList
}
var file_proto_shared_data_service_proto_depIdxs = []int32{
	0,  // 0: kyc.data.AttributeList.attributes:type_name -> kyc.data.Attribute
	4,  // 1: kyc.data.DocumentList.documents:type_name -> kyc.data.Document
	8,  // 2: kyc.data.CaseVersionList.versions:type_name -> kyc.data.CaseVersion
	15, // 3: kyc.data.CaseList.cases:type_name -> kyc.data.CaseSummary
	1,  // 4: kyc.data.DictionaryService.GetAttribute:input_type -> kyc.data.GetAttributeRequest
	2,  // 5: kyc.data.DictionaryService.ListAttributes:input_type -> kyc.data.ListAttributesRequest
	5,  // 6: kyc.data.DictionaryService.GetDocument:input_type -> kyc.data.GetDocumentRequest
	6,  // 7: kyc.data.DictionaryService.ListDocuments:input_type -> kyc.data.ListDocumentsRequest
	9,  // 8: kyc.data.CaseService.SaveCaseVersion:input_type -> kyc.data.CaseVersionRequest
	11, // 9: kyc.data.CaseService.GetCaseVersion:input_type -> kyc.data.GetCaseRequest
	12, // 10: kyc.data.CaseService.ListCaseVersions:input_type -> kyc.data.ListCaseVersionsRequest
	14, // 11: kyc.data.CaseService.ListAllCases:input_type -> kyc.data.ListAllCasesRequest
	0,  // 12: kyc.data.DictionaryService.GetAttribute:output_type -> kyc.data.Attribute
	3,  // 13: kyc.data.DictionaryService.ListAttributes:output_type -> kyc.data.AttributeList
	4,  // 14: kyc.data.DictionaryService.GetDocument:output_type -> kyc.data.Document
	7,  // 15: kyc.data.DictionaryService.ListDocuments:output_type -> kyc.data.DocumentList
	10, // 16: kyc.data.CaseService.SaveCaseVersion:output_type -> kyc.data.CaseVersionResponse
	8,  // 17: kyc.data.CaseService.GetCaseVersion:output_type -> kyc.data.CaseVersion
	13, // 18: kyc.data.CaseService.ListCaseVersions:output_type -> kyc.data.CaseVersionList
	16, // 19: kyc.data.CaseService.ListAllCases:output_type -> kyc.data.CaseList
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_shared_data_service_proto_init() }
func file_proto_shared_data_service_proto_init() {
	if File_proto_shared_data_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shared_data_service_proto_rawDesc), len(file_proto_shared_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_shared_data_service_proto_goTypes,
		DependencyIndexes: file_proto_shared_data_service_proto_depIdxs,
		MessageInfos:      file_proto_shared_data_service_proto_msgTypes,
	}.Build()
	File_proto_shared_data_service_proto = out.File
	file_proto_shared_data_service_proto_goTypes = nil
	file_proto_shared_data_service_proto_depIdxs = nil
}
