// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/cbu_graph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CbuEntity represents a legal entity in the Client Business Unit network
type CbuEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // Parent, Fund, Manager, Custodian, etc.
	Jurisdiction  string                 `protobuf:"bytes,4,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	LeiCode       string                 `protobuf:"bytes,5,opt,name=lei_code,json=leiCode,proto3" json:"lei_code,omitempty"` // Legal Entity Identifier (optional)
	TaxId         string                 `protobuf:"bytes,6,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`       // Tax identification number (optional)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	X             float32                `protobuf:"fixed32,8,opt,name=x,proto3" json:"x,omitempty"` // Optional layout hint for visualization (X coordinate)
	Y             float32                `protobuf:"fixed32,9,opt,name=y,proto3" json:"y,omitempty"` // Optional layout hint for visualization (Y coordinate)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CbuEntity) Reset() {
	*x = CbuEntity{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CbuEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CbuEntity) ProtoMessage() {}

func (x *CbuEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CbuEntity.ProtoReflect.Descriptor instead.
func (*CbuEntity) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{0}
}

func (x *CbuEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CbuEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CbuEntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CbuEntity) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *CbuEntity) GetLeiCode() string {
	if x != nil {
		return x.LeiCode
	}
	return ""
}

func (x *CbuEntity) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CbuEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CbuEntity) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CbuEntity) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// CbuRole represents a functional role in the business structure
type CbuRole struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description              string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RegulatoryClassification string                 `protobuf:"bytes,4,opt,name=regulatory_classification,json=regulatoryClassification,proto3" json:"regulatory_classification,omitempty"` // e.g., UCITS ManCo, AIFM, etc.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CbuRole) Reset() {
	*x = CbuRole{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CbuRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CbuRole) ProtoMessage() {}

func (x *CbuRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CbuRole.ProtoReflect.Descriptor instead.
func (*CbuRole) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{1}
}

func (x *CbuRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CbuRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CbuRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CbuRole) GetRegulatoryClassification() string {
	if x != nil {
		return x.RegulatoryClassification
	}
	return ""
}

// CbuRelationship represents a directional relationship between entities
type CbuRelationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                    // Source entity ID
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                          // Target entity ID
	RelationType  string                 `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`  // owns | controls | delegates | reports_to | custodies
	ControlPct    float32                `protobuf:"fixed32,5,opt,name=control_pct,json=controlPct,proto3" json:"control_pct,omitempty"`      // Percentage of control (0-100)
	RoleId        string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                    // Associated role ID
	IsBeneficial  bool                   `protobuf:"varint,7,opt,name=is_beneficial,json=isBeneficial,proto3" json:"is_beneficial,omitempty"` // True if beneficial ownership
	EffectiveDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CbuRelationship) Reset() {
	*x = CbuRelationship{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CbuRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CbuRelationship) ProtoMessage() {}

func (x *CbuRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CbuRelationship.ProtoReflect.Descriptor instead.
func (*CbuRelationship) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CbuRelationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CbuRelationship) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *CbuRelationship) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *CbuRelationship) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *CbuRelationship) GetControlPct() float32 {
	if x != nil {
		return x.ControlPct
	}
	return 0
}

func (x *CbuRelationship) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CbuRelationship) GetIsBeneficial() bool {
	if x != nil {
		return x.IsBeneficial
	}
	return false
}

func (x *CbuRelationship) GetEffectiveDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

// CbuGraph represents the complete organizational graph for a Client Business Unit
type CbuGraph struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CbuId             string                 `protobuf:"bytes,1,opt,name=cbu_id,json=cbuId,proto3" json:"cbu_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Entities          []*CbuEntity           `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Roles             []*CbuRole             `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Relationships     []*CbuRelationship     `protobuf:"bytes,6,rep,name=relationships,proto3" json:"relationships,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EntityCount       int32                  `protobuf:"varint,9,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	RelationshipCount int32                  `protobuf:"varint,10,opt,name=relationship_count,json=relationshipCount,proto3" json:"relationship_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CbuGraph) Reset() {
	*x = CbuGraph{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CbuGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CbuGraph) ProtoMessage() {}

func (x *CbuGraph) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CbuGraph.ProtoReflect.Descriptor instead.
func (*CbuGraph) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{3}
}

func (x *CbuGraph) GetCbuId() string {
	if x != nil {
		return x.CbuId
	}
	return ""
}

func (x *CbuGraph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CbuGraph) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CbuGraph) GetEntities() []*CbuEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *CbuGraph) GetRoles() []*CbuRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CbuGraph) GetRelationships() []*CbuRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *CbuGraph) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CbuGraph) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CbuGraph) GetEntityCount() int32 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *CbuGraph) GetRelationshipCount() int32 {
	if x != nil {
		return x.RelationshipCount
	}
	return 0
}

// GetCbuRequest requests a CBU graph by ID
type GetCbuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CbuId         string                 `protobuf:"bytes,1,opt,name=cbu_id,json=cbuId,proto3" json:"cbu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCbuRequest) Reset() {
	*x = GetCbuRequest{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCbuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCbuRequest) ProtoMessage() {}

func (x *GetCbuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCbuRequest.ProtoReflect.Descriptor instead.
func (*GetCbuRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{4}
}

func (x *GetCbuRequest) GetCbuId() string {
	if x != nil {
		return x.CbuId
	}
	return ""
}

// GetEntityRequest requests a specific entity
type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CbuId         string                 `protobuf:"bytes,1,opt,name=cbu_id,json=cbuId,proto3" json:"cbu_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntityRequest) GetCbuId() string {
	if x != nil {
		return x.CbuId
	}
	return ""
}

func (x *GetEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// RelationshipResponse contains relationships for an entity
type RelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Inbound       []*CbuRelationship     `protobuf:"bytes,2,rep,name=inbound,proto3" json:"inbound,omitempty"`   // Relationships pointing to this entity
	Outbound      []*CbuRelationship     `protobuf:"bytes,3,rep,name=outbound,proto3" json:"outbound,omitempty"` // Relationships from this entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipResponse) Reset() {
	*x = RelationshipResponse{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipResponse) ProtoMessage() {}

func (x *RelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipResponse.ProtoReflect.Descriptor instead.
func (*RelationshipResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{6}
}

func (x *RelationshipResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RelationshipResponse) GetInbound() []*CbuRelationship {
	if x != nil {
		return x.Inbound
	}
	return nil
}

func (x *RelationshipResponse) GetOutbound() []*CbuRelationship {
	if x != nil {
		return x.Outbound
	}
	return nil
}

// ValidationResponse contains graph validation results
type ValidationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Valid           bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Issues          []*CbuValidationIssue  `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	TotalControlPct float32                `protobuf:"fixed32,3,opt,name=total_control_pct,json=totalControlPct,proto3" json:"total_control_pct,omitempty"` // Sum of all direct ownership
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResponse) GetIssues() []*CbuValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ValidationResponse) GetTotalControlPct() float32 {
	if x != nil {
		return x.TotalControlPct
	}
	return 0
}

// ValidationIssue represents a single validation problem
type CbuValidationIssue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // error, warning, info
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EntityId       string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	RelationshipId string                 `protobuf:"bytes,4,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CbuValidationIssue) Reset() {
	*x = CbuValidationIssue{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CbuValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CbuValidationIssue) ProtoMessage() {}

func (x *CbuValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CbuValidationIssue.ProtoReflect.Descriptor instead.
func (*CbuValidationIssue) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{8}
}

func (x *CbuValidationIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CbuValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CbuValidationIssue) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CbuValidationIssue) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

// ControlChainResponse traces ownership from root to target
type ControlChainResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetEntityId      string                 `protobuf:"bytes,1,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	Chain               []*ControlLink         `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	EffectiveControlPct float32                `protobuf:"fixed32,3,opt,name=effective_control_pct,json=effectiveControlPct,proto3" json:"effective_control_pct,omitempty"` // Product of all control percentages in chain
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ControlChainResponse) Reset() {
	*x = ControlChainResponse{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlChainResponse) ProtoMessage() {}

func (x *ControlChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlChainResponse.ProtoReflect.Descriptor instead.
func (*ControlChainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{9}
}

func (x *ControlChainResponse) GetTargetEntityId() string {
	if x != nil {
		return x.TargetEntityId
	}
	return ""
}

func (x *ControlChainResponse) GetChain() []*ControlLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ControlChainResponse) GetEffectiveControlPct() float32 {
	if x != nil {
		return x.EffectiveControlPct
	}
	return 0
}

// ControlLink represents one hop in the control chain
type ControlLink struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromEntityId   string                 `protobuf:"bytes,1,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	FromEntityName string                 `protobuf:"bytes,2,opt,name=from_entity_name,json=fromEntityName,proto3" json:"from_entity_name,omitempty"`
	ToEntityId     string                 `protobuf:"bytes,3,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id,omitempty"`
	ToEntityName   string                 `protobuf:"bytes,4,opt,name=to_entity_name,json=toEntityName,proto3" json:"to_entity_name,omitempty"`
	RelationType   string                 `protobuf:"bytes,5,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	ControlPct     float32                `protobuf:"fixed32,6,opt,name=control_pct,json=controlPct,proto3" json:"control_pct,omitempty"`
	RoleId         string                 `protobuf:"bytes,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlLink) Reset() {
	*x = ControlLink{}
	mi := &file_api_proto_cbu_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlLink) ProtoMessage() {}

func (x *ControlLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbu_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlLink.ProtoReflect.Descriptor instead.
func (*ControlLink) Descriptor() ([]byte, []int) {
	return file_api_proto_cbu_graph_proto_rawDescGZIP(), []int{10}
}

func (x *ControlLink) GetFromEntityId() string {
	if x != nil {
		return x.FromEntityId
	}
	return ""
}

func (x *ControlLink) GetFromEntityName() string {
	if x != nil {
		return x.FromEntityName
	}
	return ""
}

func (x *ControlLink) GetToEntityId() string {
	if x != nil {
		return x.ToEntityId
	}
	return ""
}

func (x *ControlLink) GetToEntityName() string {
	if x != nil {
		return x.ToEntityName
	}
	return ""
}

func (x *ControlLink) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *ControlLink) GetControlPct() float32 {
	if x != nil {
		return x.ControlPct
	}
	return 0
}

func (x *ControlLink) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

var File_api_proto_cbu_graph_proto protoreflect.FileDescriptor

const file_api_proto_cbu_graph_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/cbu_graph.proto\x12\akyc.cbu\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\tCbuEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\"\n" +
	"\fjurisdiction\x18\x04 \x01(\tR\fjurisdiction\x12\x19\n" +
	"\blei_code\x18\x05 \x01(\tR\aleiCode\x12\x15\n" +
	"\x06tax_id\x18\x06 \x01(\tR\x05taxId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\f\n" +
	"\x01x\x18\b \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\t \x01(\x02R\x01y\"\x8c\x01\n" +
	"\aCbuRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\x19regulatory_classification\x18\x04 \x01(\tR\x18regulatoryClassification\"\x96\x02\n" +
	"\x0fCbuRelationship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12#\n" +
	"\rrelation_type\x18\x04 \x01(\tR\frelationType\x12\x1f\n" +
	"\vcontrol_pct\x18\x05 \x01(\x02R\n" +
	"controlPct\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12#\n" +
	"\ris_beneficial\x18\a \x01(\bR\fisBeneficial\x12A\n" +
	"\x0eeffective_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveDate\"\xb7\x03\n" +
	"\bCbuGraph\x12\x15\n" +
	"\x06cbu_id\x18\x01 \x01(\tR\x05cbuId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\bentities\x18\x04 \x03(\v2\x12.kyc.cbu.CbuEntityR\bentities\x12&\n" +
	"\x05roles\x18\x05 \x03(\v2\x10.kyc.cbu.CbuRoleR\x05roles\x12>\n" +
	"\rrelationships\x18\x06 \x03(\v2\x18.kyc.cbu.CbuRelationshipR\rrelationships\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fentity_count\x18\t \x01(\x05R\ventityCount\x12-\n" +
	"\x12relationship_count\x18\n" +
	" \x01(\x05R\x11relationshipCount\"&\n" +
	"\rGetCbuRequest\x12\x15\n" +
	"\x06cbu_id\x18\x01 \x01(\tR\x05cbuId\"F\n" +
	"\x10GetEntityRequest\x12\x15\n" +
	"\x06cbu_id\x18\x01 \x01(\tR\x05cbuId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"\x9d\x01\n" +
	"\x14RelationshipResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x122\n" +
	"\ainbound\x18\x02 \x03(\v2\x18.kyc.cbu.CbuRelationshipR\ainbound\x124\n" +
	"\boutbound\x18\x03 \x03(\v2\x18.kyc.cbu.CbuRelationshipR\boutbound\"\x8b\x01\n" +
	"\x12ValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x123\n" +
	"\x06issues\x18\x04 \x03(\v2\x1b.kyc.cbu.CbuValidationIssueR\x06issues\x12*\n" +
	"\x11total_control_pct\x18\x03 \x01(\x02R\x0ftotalControlPct\"\x90\x01\n" +
	"\x12CbuValidationIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12'\n" +
	"\x0frelationship_id\x18\x04 \x01(\tR\x0erelationshipId\"\xa0\x01\n" +
	"\x14ControlChainResponse\x12(\n" +
	"\x10target_entity_id\x18\x01 \x01(\tR\x0etargetEntityId\x12*\n" +
	"\x05chain\x18\x02 \x03(\v2\x14.kyc.cbu.ControlLinkR\x05chain\x122\n" +
	"\x15effective_control_pct\x18\x03 \x01(\x02R\x13effectiveControlPct\"\x84\x02\n" +
	"\vControlLink\x12$\n" +
	"\x0efrom_entity_id\x18\x01 \x01(\tR\ffromEntityId\x12(\n" +
	"\x10from_entity_name\x18\x02 \x01(\tR\x0efromEntityName\x12 \n" +
	"\fto_entity_id\x18\x03 \x01(\tR\n" +
	"toEntityId\x12$\n" +
	"\x0eto_entity_name\x18\x04 \x01(\tR\ftoEntityName\x12#\n" +
	"\rrelation_type\x18\x05 \x01(\tR\frelationType\x12\x1f\n" +
	"\vcontrol_pct\x18\x06 \x01(\x02R\n" +
	"controlPct\x12\x17\n" +
	"\arole_id\x18\a \x01(\tR\x06roleId2\xa3\x03\n" +
	"\x0fCbuGraphService\x125\n" +
	"\bGetGraph\x12\x16.kyc.cbu.GetCbuRequest\x1a\x11.kyc.cbu.CbuGraph\x12:\n" +
	"\tGetEntity\x12\x19.kyc.cbu.GetEntityRequest\x1a\x12.kyc.cbu.CbuEntity\x12<\n" +
	"\fListEntities\x12\x16.kyc.cbu.GetCbuRequest\x1a\x12.kyc.cbu.CbuEntity0\x01\x12L\n" +
	"\x10GetRelationships\x12\x19.kyc.cbu.GetEntityRequest\x1a\x1d.kyc.cbu.RelationshipResponse\x12D\n" +
	"\rValidateGraph\x12\x16.kyc.cbu.GetCbuRequest\x1a\x1b.kyc.cbu.ValidationResponse\x12K\n" +
	"\x0fGetControlChain\x12\x19.kyc.cbu.GetEntityRequest\x1a\x1d.kyc.cbu.ControlChainResponseB(Z&github.com/adamtc007/KYC-DSL/api/pb;pbb\x06proto3"

var (
	file_api_proto_cbu_graph_proto_rawDescOnce sync.Once
	file_api_proto_cbu_graph_proto_rawDescData []byte
)

func file_api_proto_cbu_graph_proto_rawDescGZIP() []byte {
	file_api_proto_cbu_graph_proto_rawDescOnce.Do(func() {
		file_api_proto_cbu_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cbu_graph_proto_rawDesc), len(file_api_proto_cbu_graph_proto_rawDesc)))
	})
	return file_api_proto_cbu_graph_proto_rawDescData
}

var file_api_proto_cbu_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_cbu_graph_proto_goTypes = []any{
	(*CbuEntity)(nil),             // 0: kyc.cbu.CbuEntity
	(*CbuRole)(nil),               // 1: kyc.cbu.CbuRole
	(*CbuRelationship)(nil),       // 2: kyc.cbu.CbuRelationship
	(*CbuGraph)(nil),              // 3: kyc.cbu.CbuGraph
	(*GetCbuRequest)(nil),         // 4: kyc.cbu.GetCbuRequest
	(*GetEntityRequest)(nil),      // 5: kyc.cbu.GetEntityRequest
	(*RelationshipResponse)(nil),  // 6: kyc.cbu.RelationshipResponse
	(*ValidationResponse)(nil),    // 7: kyc.cbu.ValidationResponse
	(*CbuValidationIssue)(nil),    // 8: kyc.cbu.CbuValidationIssue
	(*ControlChainResponse)(nil),  // 9: kyc.cbu.ControlChainResponse
	(*ControlLink)(nil),           // 10: kyc.cbu.ControlLink
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_proto_cbu_graph_proto_depIdxs = []int32{
	11, // 0: kyc.cbu.CbuEntity.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: kyc.cbu.CbuRelationship.effective_date:type_name -> google.protobuf.Timestamp
	0,  // 2: kyc.cbu.CbuGraph.entities:type_name -> kyc.cbu.CbuEntity
	1,  // 3: kyc.cbu.CbuGraph.roles:type_name -> kyc.cbu.CbuRole
	2,  // 4: kyc.cbu.CbuGraph.relationships:type_name -> kyc.cbu.CbuRelationship
	11, // 5: kyc.cbu.CbuGraph.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: kyc.cbu.CbuGraph.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 7: kyc.cbu.RelationshipResponse.inbound:type_name -> kyc.cbu.CbuRelationship
	2,  // 8: kyc.cbu.RelationshipResponse.outbound:type_name -> kyc.cbu.CbuRelationship
	8,  // 9: kyc.cbu.ValidationResponse.issues:type_name -> kyc.cbu.CbuValidationIssue
	10, // 10: kyc.cbu.ControlChainResponse.chain:type_name -> kyc.cbu.ControlLink
	4,  // 11: kyc.cbu.CbuGraphService.GetGraph:input_type -> kyc.cbu.GetCbuRequest
	5,  // 12: kyc.cbu.CbuGraphService.GetEntity:input_type -> kyc.cbu.GetEntityRequest
	4,  // 13: kyc.cbu.CbuGraphService.ListEntities:input_type -> kyc.cbu.GetCbuRequest
	5,  // 14: kyc.cbu.CbuGraphService.GetRelationships:input_type -> kyc.cbu.GetEntityRequest
	4,  // 15: kyc.cbu.CbuGraphService.ValidateGraph:input_type -> kyc.cbu.GetCbuRequest
	5,  // 16: kyc.cbu.CbuGraphService.GetControlChain:input_type -> kyc.cbu.GetEntityRequest
	3,  // 17: kyc.cbu.CbuGraphService.GetGraph:output_type -> kyc.cbu.CbuGraph
	0,  // 18: kyc.cbu.CbuGraphService.GetEntity:output_type -> kyc.cbu.CbuEntity
	0,  // 19: kyc.cbu.CbuGraphService.ListEntities:output_type -> kyc.cbu.CbuEntity
	6,  // 20: kyc.cbu.CbuGraphService.GetRelationships:output_type -> kyc.cbu.RelationshipResponse
	7,  // 21: kyc.cbu.CbuGraphService.ValidateGraph:output_type -> kyc.cbu.ValidationResponse
	9,  // 22: kyc.cbu.CbuGraphService.GetControlChain:output_type -> kyc.cbu.ControlChainResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_cbu_graph_proto_init() }
func file_api_proto_cbu_graph_proto_init() {
	if File_api_proto_cbu_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cbu_graph_proto_rawDesc), len(file_api_proto_cbu_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cbu_graph_proto_goTypes,
		DependencyIndexes: file_api_proto_cbu_graph_proto_depIdxs,
		MessageInfos:      file_api_proto_cbu_graph_proto_msgTypes,
	}.Build()
	File_api_proto_cbu_graph_proto = out.File
	file_api_proto_cbu_graph_proto_goTypes = nil
	file_api_proto_cbu_graph_proto_depIdxs = nil
}
