// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/kyc_case.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCaseRequest contains the case ID to retrieve
type GetCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseRequest) Reset() {
	*x = GetCaseRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseRequest) ProtoMessage() {}

func (x *GetCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseRequest.ProtoReflect.Descriptor instead.
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateCaseRequest contains updates to apply to a case
type UpdateCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCaseRequest) Reset() {
	*x = UpdateCaseRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaseRequest) ProtoMessage() {}

func (x *UpdateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCaseRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

// ListCasesRequest can include filters (currently empty)
type ListCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Jurisdiction  string                 `protobuf:"bytes,3,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Policy        string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCasesRequest) Reset() {
	*x = ListCasesRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCasesRequest) ProtoMessage() {}

func (x *ListCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCasesRequest.ProtoReflect.Descriptor instead.
func (*ListCasesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{2}
}

func (x *ListCasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCasesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCasesRequest) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *ListCasesRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

// CreateCaseRequest contains the DSL to create a new case
type CreateCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsl           string                 `protobuf:"bytes,1,opt,name=dsl,proto3" json:"dsl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCaseRequest) Reset() {
	*x = CreateCaseRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseRequest) ProtoMessage() {}

func (x *CreateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseRequest.ProtoReflect.Descriptor instead.
func (*CreateCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCaseRequest) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

// DeleteCaseRequest contains the case ID to delete
type DeleteCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCaseRequest) Reset() {
	*x = DeleteCaseRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaseRequest) ProtoMessage() {}

func (x *DeleteCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCaseResponse confirms deletion
type DeleteCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCaseResponse) Reset() {
	*x = DeleteCaseResponse{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaseResponse) ProtoMessage() {}

func (x *DeleteCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetCaseVersionsRequest retrieves all versions of a case
type GetCaseVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseName      string                 `protobuf:"bytes,1,opt,name=case_name,json=caseName,proto3" json:"case_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseVersionsRequest) Reset() {
	*x = GetCaseVersionsRequest{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseVersionsRequest) ProtoMessage() {}

func (x *GetCaseVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetCaseVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{6}
}

func (x *GetCaseVersionsRequest) GetCaseName() string {
	if x != nil {
		return x.CaseName
	}
	return ""
}

// KycCase represents a complete KYC case
type KycCase struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Jurisdiction       string                 `protobuf:"bytes,3,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Dsl                string                 `protobuf:"bytes,4,opt,name=dsl,proto3" json:"dsl,omitempty"`
	Policy             string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClientBusinessUnit string                 `protobuf:"bytes,8,opt,name=client_business_unit,json=clientBusinessUnit,proto3" json:"client_business_unit,omitempty"`
	Function           string                 `protobuf:"bytes,9,opt,name=function,proto3" json:"function,omitempty"`
	Obligation         string                 `protobuf:"bytes,10,opt,name=obligation,proto3" json:"obligation,omitempty"`
	KycToken           string                 `protobuf:"bytes,11,opt,name=kyc_token,json=kycToken,proto3" json:"kyc_token,omitempty"`
	Version            int32                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	Sha256Hash         string                 `protobuf:"bytes,13,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KycCase) Reset() {
	*x = KycCase{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycCase) ProtoMessage() {}

func (x *KycCase) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycCase.ProtoReflect.Descriptor instead.
func (*KycCase) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{7}
}

func (x *KycCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KycCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KycCase) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *KycCase) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

func (x *KycCase) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *KycCase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KycCase) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KycCase) GetClientBusinessUnit() string {
	if x != nil {
		return x.ClientBusinessUnit
	}
	return ""
}

func (x *KycCase) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *KycCase) GetObligation() string {
	if x != nil {
		return x.Obligation
	}
	return ""
}

func (x *KycCase) GetKycToken() string {
	if x != nil {
		return x.KycToken
	}
	return ""
}

func (x *KycCase) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KycCase) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

// KycCaseVersion represents a versioned snapshot of a case
type KycCaseVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseName      string                 `protobuf:"bytes,1,opt,name=case_name,json=caseName,proto3" json:"case_name,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	DslSnapshot   string                 `protobuf:"bytes,3,opt,name=dsl_snapshot,json=dslSnapshot,proto3" json:"dsl_snapshot,omitempty"`
	Sha256Hash    string                 `protobuf:"bytes,4,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	AmendmentType string                 `protobuf:"bytes,7,opt,name=amendment_type,json=amendmentType,proto3" json:"amendment_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycCaseVersion) Reset() {
	*x = KycCaseVersion{}
	mi := &file_api_proto_kyc_case_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycCaseVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycCaseVersion) ProtoMessage() {}

func (x *KycCaseVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kyc_case_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycCaseVersion.ProtoReflect.Descriptor instead.
func (*KycCaseVersion) Descriptor() ([]byte, []int) {
	return file_api_proto_kyc_case_proto_rawDescGZIP(), []int{8}
}

func (x *KycCaseVersion) GetCaseName() string {
	if x != nil {
		return x.CaseName
	}
	return ""
}

func (x *KycCaseVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KycCaseVersion) GetDslSnapshot() string {
	if x != nil {
		return x.DslSnapshot
	}
	return ""
}

func (x *KycCaseVersion) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

func (x *KycCaseVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KycCaseVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *KycCaseVersion) GetAmendmentType() string {
	if x != nil {
		return x.AmendmentType
	}
	return ""
}

var File_api_proto_kyc_case_proto protoreflect.FileDescriptor

const file_api_proto_kyc_case_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/kyc_case.proto\x12\x03kyc\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9e\x01\n" +
	"\x11UpdateCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\aupdates\x18\x02 \x03(\v2#.kyc.UpdateCaseRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x10ListCasesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\"\n" +
	"\fjurisdiction\x18\x03 \x01(\tR\fjurisdiction\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\"%\n" +
	"\x11CreateCaseRequest\x12\x10\n" +
	"\x03dsl\x18\x01 \x01(\tR\x03dsl\"#\n" +
	"\x11DeleteCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeleteCaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x16GetCaseVersionsRequest\x12\x1b\n" +
	"\tcase_name\x18\x01 \x01(\tR\bcaseName\"\xb7\x03\n" +
	"\aKycCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fjurisdiction\x18\x03 \x01(\tR\fjurisdiction\x12\x10\n" +
	"\x03dsl\x18\x04 \x01(\tR\x03dsl\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x14client_business_unit\x18\b \x01(\tR\x12clientBusinessUnit\x12\x1a\n" +
	"\bfunction\x18\t \x01(\tR\bfunction\x12\x1e\n" +
	"\n" +
	"obligation\x18\n" +
	" \x01(\tR\n" +
	"obligation\x12\x1b\n" +
	"\tkyc_token\x18\v \x01(\tR\bkycToken\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversion\x12\x1f\n" +
	"\vsha256_hash\x18\r \x01(\tR\n" +
	"sha256Hash\"\x8c\x02\n" +
	"\x0eKycCaseVersion\x12\x1b\n" +
	"\tcase_name\x18\x01 \x01(\tR\bcaseName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12!\n" +
	"\fdsl_snapshot\x18\x03 \x01(\tR\vdslSnapshot\x12\x1f\n" +
	"\vsha256_hash\x18\x04 \x01(\tR\n" +
	"sha256Hash\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12%\n" +
	"\x0eamendment_type\x18\a \x01(\tR\ramendmentType2\xe0\x02\n" +
	"\x0eKycCaseService\x12,\n" +
	"\aGetCase\x12\x13.kyc.GetCaseRequest\x1a\f.kyc.KycCase\x122\n" +
	"\n" +
	"UpdateCase\x12\x16.kyc.UpdateCaseRequest\x1a\f.kyc.KycCase\x122\n" +
	"\tListCases\x12\x15.kyc.ListCasesRequest\x1a\f.kyc.KycCase0\x01\x122\n" +
	"\n" +
	"CreateCase\x12\x16.kyc.CreateCaseRequest\x1a\f.kyc.KycCase\x12=\n" +
	"\n" +
	"DeleteCase\x12\x16.kyc.DeleteCaseRequest\x1a\x17.kyc.DeleteCaseResponse\x12E\n" +
	"\x0fGetCaseVersions\x12\x1b.kyc.GetCaseVersionsRequest\x1a\x13.kyc.KycCaseVersion0\x01B(Z&github.com/adamtc007/KYC-DSL/api/pb;pbb\x06proto3"

var (
	file_api_proto_kyc_case_proto_rawDescOnce sync.Once
	file_api_proto_kyc_case_proto_rawDescData []byte
)

func file_api_proto_kyc_case_proto_rawDescGZIP() []byte {
	file_api_proto_kyc_case_proto_rawDescOnce.Do(func() {
		file_api_proto_kyc_case_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kyc_case_proto_rawDesc), len(file_api_proto_kyc_case_proto_rawDesc)))
	})
	return file_api_proto_kyc_case_proto_rawDescData
}

var file_api_proto_kyc_case_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_kyc_case_proto_goTypes = []any{
	(*GetCaseRequest)(nil),         // 0: kyc.GetCaseRequest
	(*UpdateCaseRequest)(nil),      // 1: kyc.UpdateCaseRequest
	(*ListCasesRequest)(nil),       // 2: kyc.ListCasesRequest
	(*CreateCaseRequest)(nil),      // 3: kyc.CreateCaseRequest
	(*DeleteCaseRequest)(nil),      // 4: kyc.DeleteCaseRequest
	(*DeleteCaseResponse)(nil),     // 5: kyc.DeleteCaseResponse
	(*GetCaseVersionsRequest)(nil), // 6: kyc.GetCaseVersionsRequest
	(*KycCase)(nil),                // 7: kyc.KycCase
	(*KycCaseVersion)(nil),         // 8: kyc.KycCaseVersion
	nil,                            // 9: kyc.UpdateCaseRequest.UpdatesEntry
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_api_proto_kyc_case_proto_depIdxs = []int32{
	9,  // 0: kyc.UpdateCaseRequest.updates:type_name -> kyc.UpdateCaseRequest.UpdatesEntry
	10, // 1: kyc.KycCase.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: kyc.KycCase.updated_at:type_name -> google.protobuf.Timestamp
	10, // 3: kyc.KycCaseVersion.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: kyc.KycCaseService.GetCase:input_type -> kyc.GetCaseRequest
	1,  // 5: kyc.KycCaseService.UpdateCase:input_type -> kyc.UpdateCaseRequest
	2,  // 6: kyc.KycCaseService.ListCases:input_type -> kyc.ListCasesRequest
	3,  // 7: kyc.KycCaseService.CreateCase:input_type -> kyc.CreateCaseRequest
	4,  // 8: kyc.KycCaseService.DeleteCase:input_type -> kyc.DeleteCaseRequest
	6,  // 9: kyc.KycCaseService.GetCaseVersions:input_type -> kyc.GetCaseVersionsRequest
	7,  // 10: kyc.KycCaseService.GetCase:output_type -> kyc.KycCase
	7,  // 11: kyc.KycCaseService.UpdateCase:output_type -> kyc.KycCase
	7,  // 12: kyc.KycCaseService.ListCases:output_type -> kyc.KycCase
	7,  // 13: kyc.KycCaseService.CreateCase:output_type -> kyc.KycCase
	5,  // 14: kyc.KycCaseService.DeleteCase:output_type -> kyc.DeleteCaseResponse
	8,  // 15: kyc.KycCaseService.GetCaseVersions:output_type -> kyc.KycCaseVersion
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_kyc_case_proto_init() }
func file_api_proto_kyc_case_proto_init() {
	if File_api_proto_kyc_case_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kyc_case_proto_rawDesc), len(file_api_proto_kyc_case_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kyc_case_proto_goTypes,
		DependencyIndexes: file_api_proto_kyc_case_proto_depIdxs,
		MessageInfos:      file_api_proto_kyc_case_proto_msgTypes,
	}.Build()
	File_api_proto_kyc_case_proto = out.File
	file_api_proto_kyc_case_proto_goTypes = nil
	file_api_proto_kyc_case_proto_depIdxs = nil
}
