// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/dictionary_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attribute represents a data attribute in the KYC data model
type Attribute struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                  // Unique attribute ID (e.g., "attr-abc123")
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // Attribute name (e.g., "Full Name", "Date of Birth")
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                // Human-readable description
	DataType        string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`                      // Data type (e.g., "string", "date", "number")
	Required        bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`                                     // Whether this attribute is required
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`                                      // Category (e.g., "identity", "address", "financial")
	ValidationRules []string               `protobuf:"bytes,7,rep,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"` // Validation rules (e.g., "regex:^[A-Z]", "min_length:5")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Attribute) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Attribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Attribute) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Attribute) GetValidationRules() []string {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

// CreateAttributeRequest to add a new attribute
type CreateAttributeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DataType        string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Required        bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ValidationRules []string               `protobuf:"bytes,6,rep,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAttributeRequest) Reset() {
	*x = CreateAttributeRequest{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeRequest) ProtoMessage() {}

func (x *CreateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAttributeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAttributeRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *CreateAttributeRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CreateAttributeRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAttributeRequest) GetValidationRules() []string {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

// DictGetAttributeRequest to retrieve a specific attribute by ID
type DictGetAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Attribute ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictGetAttributeRequest) Reset() {
	*x = DictGetAttributeRequest{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictGetAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictGetAttributeRequest) ProtoMessage() {}

func (x *DictGetAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictGetAttributeRequest.ProtoReflect.Descriptor instead.
func (*DictGetAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{2}
}

func (x *DictGetAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SearchAttributesRequest to search attributes
type SearchAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`  // Search query (searches name and description)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Optional: limit number of results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAttributesRequest) Reset() {
	*x = SearchAttributesRequest{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAttributesRequest) ProtoMessage() {}

func (x *SearchAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAttributesRequest.ProtoReflect.Descriptor instead.
func (*SearchAttributesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchAttributesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchAttributesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchAttributesResponse contains matching attributes
type SearchAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAttributesResponse) Reset() {
	*x = SearchAttributesResponse{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAttributesResponse) ProtoMessage() {}

func (x *SearchAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAttributesResponse.ProtoReflect.Descriptor instead.
func (*SearchAttributesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SearchAttributesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ListAttributesRequest to get all attributes
type ListAttributesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Optional: limit number of results
	Offset         int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Optional: offset for pagination
	CategoryFilter string                 `protobuf:"bytes,3,opt,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"` // Optional: filter by category
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAttributesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAttributesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAttributesRequest) GetCategoryFilter() string {
	if x != nil {
		return x.CategoryFilter
	}
	return ""
}

// ListAttributesResponse contains all attributes
type ListAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesResponse) Reset() {
	*x = ListAttributesResponse{}
	mi := &file_api_proto_dictionary_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesResponse) ProtoMessage() {}

func (x *ListAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dictionary_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dictionary_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListAttributesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_proto_dictionary_service_proto protoreflect.FileDescriptor

const file_api_proto_dictionary_service_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/dictionary_service.proto\x12\x0ekyc.dictionary\"\xd1\x01\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12)\n" +
	"\x10validation_rules\x18\a \x03(\tR\x0fvalidationRules\"\xce\x01\n" +
	"\x16CreateAttributeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12)\n" +
	"\x10validation_rules\x18\x06 \x03(\tR\x0fvalidationRules\")\n" +
	"\x17DictGetAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x17SearchAttributesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"v\n" +
	"\x18SearchAttributesResponse\x129\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x19.kyc.dictionary.AttributeR\n" +
	"attributes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"n\n" +
	"\x15ListAttributesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12'\n" +
	"\x0fcategory_filter\x18\x03 \x01(\tR\x0ecategoryFilter\"t\n" +
	"\x16ListAttributesResponse\x129\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x19.kyc.dictionary.AttributeR\n" +
	"attributes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\x85\x03\n" +
	"\x11DictionaryService\x12T\n" +
	"\x0fCreateAttribute\x12&.kyc.dictionary.CreateAttributeRequest\x1a\x19.kyc.dictionary.Attribute\x12R\n" +
	"\fGetAttribute\x12'.kyc.dictionary.DictGetAttributeRequest\x1a\x19.kyc.dictionary.Attribute\x12e\n" +
	"\x10SearchAttributes\x12'.kyc.dictionary.SearchAttributesRequest\x1a(.kyc.dictionary.SearchAttributesResponse\x12_\n" +
	"\x0eListAttributes\x12%.kyc.dictionary.ListAttributesRequest\x1a&.kyc.dictionary.ListAttributesResponseB(Z&github.com/adamtc007/KYC-DSL/api/pb;pbb\x06proto3"

var (
	file_api_proto_dictionary_service_proto_rawDescOnce sync.Once
	file_api_proto_dictionary_service_proto_rawDescData []byte
)

func file_api_proto_dictionary_service_proto_rawDescGZIP() []byte {
	file_api_proto_dictionary_service_proto_rawDescOnce.Do(func() {
		file_api_proto_dictionary_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dictionary_service_proto_rawDesc), len(file_api_proto_dictionary_service_proto_rawDesc)))
	})
	return file_api_proto_dictionary_service_proto_rawDescData
}

var file_api_proto_dictionary_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_dictionary_service_proto_goTypes = []any{
	(*Attribute)(nil),                // 0: kyc.dictionary.Attribute
	(*CreateAttributeRequest)(nil),   // 1: kyc.dictionary.CreateAttributeRequest
	(*DictGetAttributeRequest)(nil),  // 2: kyc.dictionary.DictGetAttributeRequest
	(*SearchAttributesRequest)(nil),  // 3: kyc.dictionary.SearchAttributesRequest
	(*SearchAttributesResponse)(nil), // 4: kyc.dictionary.SearchAttributesResponse
	(*ListAttributesRequest)(nil),    // 5: kyc.dictionary.ListAttributesRequest
	(*ListAttributesResponse)(nil),   // 6: kyc.dictionary.ListAttributesResponse
}
var file_api_proto_dictionary_service_proto_depIdxs = []int32{
	0, // 0: kyc.dictionary.SearchAttributesResponse.attributes:type_name -> kyc.dictionary.Attribute
	0, // 1: kyc.dictionary.ListAttributesResponse.attributes:type_name -> kyc.dictionary.Attribute
	1, // 2: kyc.dictionary.DictionaryService.CreateAttribute:input_type -> kyc.dictionary.CreateAttributeRequest
	2, // 3: kyc.dictionary.DictionaryService.GetAttribute:input_type -> kyc.dictionary.DictGetAttributeRequest
	3, // 4: kyc.dictionary.DictionaryService.SearchAttributes:input_type -> kyc.dictionary.SearchAttributesRequest
	5, // 5: kyc.dictionary.DictionaryService.ListAttributes:input_type -> kyc.dictionary.ListAttributesRequest
	0, // 6: kyc.dictionary.DictionaryService.CreateAttribute:output_type -> kyc.dictionary.Attribute
	0, // 7: kyc.dictionary.DictionaryService.GetAttribute:output_type -> kyc.dictionary.Attribute
	4, // 8: kyc.dictionary.DictionaryService.SearchAttributes:output_type -> kyc.dictionary.SearchAttributesResponse
	6, // 9: kyc.dictionary.DictionaryService.ListAttributes:output_type -> kyc.dictionary.ListAttributesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_dictionary_service_proto_init() }
func file_api_proto_dictionary_service_proto_init() {
	if File_api_proto_dictionary_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dictionary_service_proto_rawDesc), len(file_api_proto_dictionary_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dictionary_service_proto_goTypes,
		DependencyIndexes: file_api_proto_dictionary_service_proto_depIdxs,
		MessageInfos:      file_api_proto_dictionary_service_proto_msgTypes,
	}.Build()
	File_api_proto_dictionary_service_proto = out.File
	file_api_proto_dictionary_service_proto_goTypes = nil
	file_api_proto_dictionary_service_proto_depIdxs = nil
}
