// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/dsl_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest contains the case and function to execute
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Arguments     map[string]string      `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ExecuteRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ExecuteRequest) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// ExecuteResponse contains the result of execution
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedDsl    string                 `protobuf:"bytes,1,opt,name=updated_dsl,json=updatedDsl,proto3" json:"updated_dsl,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	CaseId        string                 `protobuf:"bytes,4,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	NewVersion    int32                  `protobuf:"varint,5,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetUpdatedDsl() string {
	if x != nil {
		return x.UpdatedDsl
	}
	return ""
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ExecuteResponse) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

// ValidateRequest contains the case to validate
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Dsl           string                 `protobuf:"bytes,2,opt,name=dsl,proto3" json:"dsl,omitempty"` // Optional: validate DSL without persisting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ValidateRequest) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

// ValidationResult contains validation outcome
type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Issues        []*ValidationIssue     `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidationResult) GetIssues() []*ValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

// ValidationIssue represents a single validation issue
type ValidationIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // error, warning, info
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationIssue) Reset() {
	*x = ValidationIssue{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationIssue) ProtoMessage() {}

func (x *ValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationIssue.ProtoReflect.Descriptor instead.
func (*ValidationIssue) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationIssue) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidationIssue) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ValidationIssue) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// ParseRequest contains DSL text to parse
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsl           string                 `protobuf:"bytes,1,opt,name=dsl,proto3" json:"dsl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{5}
}

func (x *ParseRequest) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

// ParseResponse contains the parsed structure
type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cases         []*ParsedCase          `protobuf:"bytes,3,rep,name=cases,proto3" json:"cases,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{6}
}

func (x *ParseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseResponse) GetCases() []*ParsedCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *ParseResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ParsedCase represents a parsed KYC case structure
type ParsedCase struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nature               string                 `protobuf:"bytes,2,opt,name=nature,proto3" json:"nature,omitempty"`
	Purpose              string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ClientBusinessUnit   string                 `protobuf:"bytes,4,opt,name=client_business_unit,json=clientBusinessUnit,proto3" json:"client_business_unit,omitempty"`
	Policy               string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	Function             string                 `protobuf:"bytes,6,opt,name=function,proto3" json:"function,omitempty"`
	Obligation           string                 `protobuf:"bytes,7,opt,name=obligation,proto3" json:"obligation,omitempty"`
	KycToken             string                 `protobuf:"bytes,8,opt,name=kyc_token,json=kycToken,proto3" json:"kyc_token,omitempty"`
	Ownership            *OwnershipStructure    `protobuf:"bytes,9,opt,name=ownership,proto3" json:"ownership,omitempty"`
	DataDictionary       *DataDictionary        `protobuf:"bytes,10,opt,name=data_dictionary,json=dataDictionary,proto3" json:"data_dictionary,omitempty"`
	DocumentRequirements *DocumentRequirements  `protobuf:"bytes,11,opt,name=document_requirements,json=documentRequirements,proto3" json:"document_requirements,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParsedCase) Reset() {
	*x = ParsedCase{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedCase) ProtoMessage() {}

func (x *ParsedCase) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedCase.ProtoReflect.Descriptor instead.
func (*ParsedCase) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{7}
}

func (x *ParsedCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParsedCase) GetNature() string {
	if x != nil {
		return x.Nature
	}
	return ""
}

func (x *ParsedCase) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ParsedCase) GetClientBusinessUnit() string {
	if x != nil {
		return x.ClientBusinessUnit
	}
	return ""
}

func (x *ParsedCase) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *ParsedCase) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ParsedCase) GetObligation() string {
	if x != nil {
		return x.Obligation
	}
	return ""
}

func (x *ParsedCase) GetKycToken() string {
	if x != nil {
		return x.KycToken
	}
	return ""
}

func (x *ParsedCase) GetOwnership() *OwnershipStructure {
	if x != nil {
		return x.Ownership
	}
	return nil
}

func (x *ParsedCase) GetDataDictionary() *DataDictionary {
	if x != nil {
		return x.DataDictionary
	}
	return nil
}

func (x *ParsedCase) GetDocumentRequirements() *DocumentRequirements {
	if x != nil {
		return x.DocumentRequirements
	}
	return nil
}

// OwnershipStructure represents ownership details
type OwnershipStructure struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntityName       string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Owners           []*Owner               `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	BeneficialOwners []*BeneficialOwner     `protobuf:"bytes,3,rep,name=beneficial_owners,json=beneficialOwners,proto3" json:"beneficial_owners,omitempty"`
	Controllers      []*Controller          `protobuf:"bytes,4,rep,name=controllers,proto3" json:"controllers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OwnershipStructure) Reset() {
	*x = OwnershipStructure{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipStructure) ProtoMessage() {}

func (x *OwnershipStructure) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipStructure.ProtoReflect.Descriptor instead.
func (*OwnershipStructure) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{8}
}

func (x *OwnershipStructure) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *OwnershipStructure) GetOwners() []*Owner {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *OwnershipStructure) GetBeneficialOwners() []*BeneficialOwner {
	if x != nil {
		return x.BeneficialOwners
	}
	return nil
}

func (x *OwnershipStructure) GetControllers() []*Controller {
	if x != nil {
		return x.Controllers
	}
	return nil
}

// Owner represents an ownership stake
type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{9}
}

func (x *Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Owner) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// BeneficialOwner represents a beneficial ownership stake
type BeneficialOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeneficialOwner) Reset() {
	*x = BeneficialOwner{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeneficialOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeneficialOwner) ProtoMessage() {}

func (x *BeneficialOwner) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeneficialOwner.ProtoReflect.Descriptor instead.
func (*BeneficialOwner) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{10}
}

func (x *BeneficialOwner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeneficialOwner) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Controller represents a controlling party
type Controller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Controller) Reset() {
	*x = Controller{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Controller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controller) ProtoMessage() {}

func (x *Controller) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controller.ProtoReflect.Descriptor instead.
func (*Controller) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{11}
}

func (x *Controller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Controller) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// DataDictionary represents attribute sources
type DataDictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*AttributeDefinition `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDictionary) Reset() {
	*x = DataDictionary{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDictionary) ProtoMessage() {}

func (x *DataDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDictionary.ProtoReflect.Descriptor instead.
func (*DataDictionary) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{12}
}

func (x *DataDictionary) GetAttributes() []*AttributeDefinition {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// AttributeDefinition represents a single attribute's sources
type AttributeDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PrimarySources   []string               `protobuf:"bytes,2,rep,name=primary_sources,json=primarySources,proto3" json:"primary_sources,omitempty"`
	SecondarySources []string               `protobuf:"bytes,3,rep,name=secondary_sources,json=secondarySources,proto3" json:"secondary_sources,omitempty"`
	TertiarySources  []string               `protobuf:"bytes,4,rep,name=tertiary_sources,json=tertiarySources,proto3" json:"tertiary_sources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{13}
}

func (x *AttributeDefinition) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AttributeDefinition) GetPrimarySources() []string {
	if x != nil {
		return x.PrimarySources
	}
	return nil
}

func (x *AttributeDefinition) GetSecondarySources() []string {
	if x != nil {
		return x.SecondarySources
	}
	return nil
}

func (x *AttributeDefinition) GetTertiarySources() []string {
	if x != nil {
		return x.TertiarySources
	}
	return nil
}

// DocumentRequirements represents required documents
type DocumentRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jurisdiction  string                 `protobuf:"bytes,1,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Required      []*DocumentRequirement `protobuf:"bytes,2,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRequirements) Reset() {
	*x = DocumentRequirements{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequirements) ProtoMessage() {}

func (x *DocumentRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequirements.ProtoReflect.Descriptor instead.
func (*DocumentRequirements) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{14}
}

func (x *DocumentRequirements) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *DocumentRequirements) GetRequired() []*DocumentRequirement {
	if x != nil {
		return x.Required
	}
	return nil
}

// DocumentRequirement represents a required document
type DocumentRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRequirement) Reset() {
	*x = DocumentRequirement{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequirement) ProtoMessage() {}

func (x *DocumentRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequirement.ProtoReflect.Descriptor instead.
func (*DocumentRequirement) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{15}
}

func (x *DocumentRequirement) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DocumentRequirement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SerializeRequest contains structured case to serialize
type SerializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Case          *ParsedCase            `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeRequest) Reset() {
	*x = SerializeRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeRequest) ProtoMessage() {}

func (x *SerializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeRequest.ProtoReflect.Descriptor instead.
func (*SerializeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{16}
}

func (x *SerializeRequest) GetCase() *ParsedCase {
	if x != nil {
		return x.Case
	}
	return nil
}

// SerializeResponse contains the DSL representation
type SerializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Dsl           string                 `protobuf:"bytes,2,opt,name=dsl,proto3" json:"dsl,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeResponse) Reset() {
	*x = SerializeResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeResponse) ProtoMessage() {}

func (x *SerializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeResponse.ProtoReflect.Descriptor instead.
func (*SerializeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{17}
}

func (x *SerializeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SerializeResponse) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

func (x *SerializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AmendRequest contains amendment to apply
type AmendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseName      string                 `protobuf:"bytes,1,opt,name=case_name,json=caseName,proto3" json:"case_name,omitempty"`
	AmendmentType string                 `protobuf:"bytes,2,opt,name=amendment_type,json=amendmentType,proto3" json:"amendment_type,omitempty"` // policy-discovery, document-discovery, etc.
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendRequest) Reset() {
	*x = AmendRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendRequest) ProtoMessage() {}

func (x *AmendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendRequest.ProtoReflect.Descriptor instead.
func (*AmendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{18}
}

func (x *AmendRequest) GetCaseName() string {
	if x != nil {
		return x.CaseName
	}
	return ""
}

func (x *AmendRequest) GetAmendmentType() string {
	if x != nil {
		return x.AmendmentType
	}
	return ""
}

func (x *AmendRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// AmendResponse contains the amended case
type AmendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedDsl    string                 `protobuf:"bytes,3,opt,name=updated_dsl,json=updatedDsl,proto3" json:"updated_dsl,omitempty"`
	NewVersion    int32                  `protobuf:"varint,4,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Sha256Hash    string                 `protobuf:"bytes,5,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendResponse) Reset() {
	*x = AmendResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendResponse) ProtoMessage() {}

func (x *AmendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendResponse.ProtoReflect.Descriptor instead.
func (*AmendResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{19}
}

func (x *AmendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AmendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AmendResponse) GetUpdatedDsl() string {
	if x != nil {
		return x.UpdatedDsl
	}
	return ""
}

func (x *AmendResponse) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *AmendResponse) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

// ListAmendmentsRequest can include filters
type ListAmendmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAmendmentsRequest) Reset() {
	*x = ListAmendmentsRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAmendmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmendmentsRequest) ProtoMessage() {}

func (x *ListAmendmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmendmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAmendmentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{20}
}

// ListAmendmentsResponse contains available amendments
type ListAmendmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amendments    []*AmendmentType       `protobuf:"bytes,1,rep,name=amendments,proto3" json:"amendments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAmendmentsResponse) Reset() {
	*x = ListAmendmentsResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAmendmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmendmentsResponse) ProtoMessage() {}

func (x *ListAmendmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmendmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAmendmentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListAmendmentsResponse) GetAmendments() []*AmendmentType {
	if x != nil {
		return x.Amendments
	}
	return nil
}

// AmendmentType describes an available amendment
type AmendmentType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []string               `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendmentType) Reset() {
	*x = AmendmentType{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendmentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendmentType) ProtoMessage() {}

func (x *AmendmentType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendmentType.ProtoReflect.Descriptor instead.
func (*AmendmentType) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{22}
}

func (x *AmendmentType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AmendmentType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AmendmentType) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GetGrammarRequest retrieves grammar info
type GetGrammarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrammarRequest) Reset() {
	*x = GetGrammarRequest{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrammarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrammarRequest) ProtoMessage() {}

func (x *GetGrammarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrammarRequest.ProtoReflect.Descriptor instead.
func (*GetGrammarRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{23}
}

// GrammarResponse contains the DSL grammar
type GrammarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ebnf          string                 `protobuf:"bytes,1,opt,name=ebnf,proto3" json:"ebnf,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrammarResponse) Reset() {
	*x = GrammarResponse{}
	mi := &file_api_proto_dsl_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrammarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrammarResponse) ProtoMessage() {}

func (x *GrammarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsl_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrammarResponse.ProtoReflect.Descriptor instead.
func (*GrammarResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsl_service_proto_rawDescGZIP(), []int{24}
}

func (x *GrammarResponse) GetEbnf() string {
	if x != nil {
		return x.Ebnf
	}
	return ""
}

func (x *GrammarResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GrammarResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_dsl_service_proto protoreflect.FileDescriptor

const file_api_proto_dsl_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/dsl_service.proto\x12\akyc.dsl\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12D\n" +
	"\targuments\x18\x03 \x03(\v2&.kyc.dsl.ExecuteRequest.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x0fExecuteResponse\x12\x1f\n" +
	"\vupdated_dsl\x18\x01 \x01(\tR\n" +
	"updatedDsl\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x17\n" +
	"\acase_id\x18\x04 \x01(\tR\x06caseId\x12\x1f\n" +
	"\vnew_version\x18\x05 \x01(\x05R\n" +
	"newVersion\"<\n" +
	"\x0fValidateRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x10\n" +
	"\x03dsl\x18\x02 \x01(\tR\x03dsl\"\x8e\x01\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x120\n" +
	"\x06issues\x18\x04 \x03(\v2\x18.kyc.dsl.ValidationIssueR\x06issues\"\x87\x01\n" +
	"\x0fValidationIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\" \n" +
	"\fParseRequest\x12\x10\n" +
	"\x03dsl\x18\x01 \x01(\tR\x03dsl\"\x86\x01\n" +
	"\rParseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05cases\x18\x03 \x03(\v2\x13.kyc.dsl.ParsedCaseR\x05cases\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\xc6\x03\n" +
	"\n" +
	"ParsedCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06nature\x18\x02 \x01(\tR\x06nature\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x120\n" +
	"\x14client_business_unit\x18\x04 \x01(\tR\x12clientBusinessUnit\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x12\x1a\n" +
	"\bfunction\x18\x06 \x01(\tR\bfunction\x12\x1e\n" +
	"\n" +
	"obligation\x18\a \x01(\tR\n" +
	"obligation\x12\x1b\n" +
	"\tkyc_token\x18\b \x01(\tR\bkycToken\x129\n" +
	"\townership\x18\t \x01(\v2\x1b.kyc.dsl.OwnershipStructureR\townership\x12@\n" +
	"\x0fdata_dictionary\x18\n" +
	" \x01(\v2\x17.kyc.dsl.DataDictionaryR\x0edataDictionary\x12R\n" +
	"\x15document_requirements\x18\v \x01(\v2\x1d.kyc.dsl.DocumentRequirementsR\x14documentRequirements\"\xdb\x01\n" +
	"\x12OwnershipStructure\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12&\n" +
	"\x06owners\x18\x02 \x03(\v2\x0e.kyc.dsl.OwnerR\x06owners\x12E\n" +
	"\x11beneficial_owners\x18\x03 \x03(\v2\x18.kyc.dsl.BeneficialOwnerR\x10beneficialOwners\x125\n" +
	"\vcontrollers\x18\x04 \x03(\v2\x13.kyc.dsl.ControllerR\vcontrollers\";\n" +
	"\x05Owner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\"E\n" +
	"\x0fBeneficialOwner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\"4\n" +
	"\n" +
	"Controller\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"N\n" +
	"\x0eDataDictionary\x12<\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1c.kyc.dsl.AttributeDefinitionR\n" +
	"attributes\"\xaa\x01\n" +
	"\x13AttributeDefinition\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12'\n" +
	"\x0fprimary_sources\x18\x02 \x03(\tR\x0eprimarySources\x12+\n" +
	"\x11secondary_sources\x18\x03 \x03(\tR\x10secondarySources\x12)\n" +
	"\x10tertiary_sources\x18\x04 \x03(\tR\x0ftertiarySources\"t\n" +
	"\x14DocumentRequirements\x12\"\n" +
	"\fjurisdiction\x18\x01 \x01(\tR\fjurisdiction\x128\n" +
	"\brequired\x18\x02 \x03(\v2\x1c.kyc.dsl.DocumentRequirementR\brequired\"=\n" +
	"\x13DocumentRequirement\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\x10SerializeRequest\x12'\n" +
	"\x04case\x18\x01 \x01(\v2\x13.kyc.dsl.ParsedCaseR\x04case\"Y\n" +
	"\x11SerializeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03dsl\x18\x02 \x01(\tR\x03dsl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd8\x01\n" +
	"\fAmendRequest\x12\x1b\n" +
	"\tcase_name\x18\x01 \x01(\tR\bcaseName\x12%\n" +
	"\x0eamendment_type\x18\x02 \x01(\tR\ramendmentType\x12E\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2%.kyc.dsl.AmendRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\rAmendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vupdated_dsl\x18\x03 \x01(\tR\n" +
	"updatedDsl\x12\x1f\n" +
	"\vnew_version\x18\x04 \x01(\x05R\n" +
	"newVersion\x12\x1f\n" +
	"\vsha256_hash\x18\x05 \x01(\tR\n" +
	"sha256Hash\"\x17\n" +
	"\x15ListAmendmentsRequest\"P\n" +
	"\x16ListAmendmentsResponse\x126\n" +
	"\n" +
	"amendments\x18\x01 \x03(\v2\x16.kyc.dsl.AmendmentTypeR\n" +
	"amendments\"e\n" +
	"\rAmendmentType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\"\x13\n" +
	"\x11GetGrammarRequest\"z\n" +
	"\x0fGrammarResponse\x12\x12\n" +
	"\x04ebnf\x18\x01 \x01(\tR\x04ebnf\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xd6\x03\n" +
	"\n" +
	"DslService\x12<\n" +
	"\aExecute\x12\x17.kyc.dsl.ExecuteRequest\x1a\x18.kyc.dsl.ExecuteResponse\x12?\n" +
	"\bValidate\x12\x18.kyc.dsl.ValidateRequest\x1a\x19.kyc.dsl.ValidationResult\x126\n" +
	"\x05Parse\x12\x15.kyc.dsl.ParseRequest\x1a\x16.kyc.dsl.ParseResponse\x12B\n" +
	"\tSerialize\x12\x19.kyc.dsl.SerializeRequest\x1a\x1a.kyc.dsl.SerializeResponse\x126\n" +
	"\x05Amend\x12\x15.kyc.dsl.AmendRequest\x1a\x16.kyc.dsl.AmendResponse\x12Q\n" +
	"\x0eListAmendments\x12\x1e.kyc.dsl.ListAmendmentsRequest\x1a\x1f.kyc.dsl.ListAmendmentsResponse\x12B\n" +
	"\n" +
	"GetGrammar\x12\x1a.kyc.dsl.GetGrammarRequest\x1a\x18.kyc.dsl.GrammarResponseB(Z&github.com/adamtc007/KYC-DSL/api/pb;pbb\x06proto3"

var (
	file_api_proto_dsl_service_proto_rawDescOnce sync.Once
	file_api_proto_dsl_service_proto_rawDescData []byte
)

func file_api_proto_dsl_service_proto_rawDescGZIP() []byte {
	file_api_proto_dsl_service_proto_rawDescOnce.Do(func() {
		file_api_proto_dsl_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dsl_service_proto_rawDesc), len(file_api_proto_dsl_service_proto_rawDesc)))
	})
	return file_api_proto_dsl_service_proto_rawDescData
}

var file_api_proto_dsl_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_proto_dsl_service_proto_goTypes = []any{
	(*ExecuteRequest)(nil),         // 0: kyc.dsl.ExecuteRequest
	(*ExecuteResponse)(nil),        // 1: kyc.dsl.ExecuteResponse
	(*ValidateRequest)(nil),        // 2: kyc.dsl.ValidateRequest
	(*ValidationResult)(nil),       // 3: kyc.dsl.ValidationResult
	(*ValidationIssue)(nil),        // 4: kyc.dsl.ValidationIssue
	(*ParseRequest)(nil),           // 5: kyc.dsl.ParseRequest
	(*ParseResponse)(nil),          // 6: kyc.dsl.ParseResponse
	(*ParsedCase)(nil),             // 7: kyc.dsl.ParsedCase
	(*OwnershipStructure)(nil),     // 8: kyc.dsl.OwnershipStructure
	(*Owner)(nil),                  // 9: kyc.dsl.Owner
	(*BeneficialOwner)(nil),        // 10: kyc.dsl.BeneficialOwner
	(*Controller)(nil),             // 11: kyc.dsl.Controller
	(*DataDictionary)(nil),         // 12: kyc.dsl.DataDictionary
	(*AttributeDefinition)(nil),    // 13: kyc.dsl.AttributeDefinition
	(*DocumentRequirements)(nil),   // 14: kyc.dsl.DocumentRequirements
	(*DocumentRequirement)(nil),    // 15: kyc.dsl.DocumentRequirement
	(*SerializeRequest)(nil),       // 16: kyc.dsl.SerializeRequest
	(*SerializeResponse)(nil),      // 17: kyc.dsl.SerializeResponse
	(*AmendRequest)(nil),           // 18: kyc.dsl.AmendRequest
	(*AmendResponse)(nil),          // 19: kyc.dsl.AmendResponse
	(*ListAmendmentsRequest)(nil),  // 20: kyc.dsl.ListAmendmentsRequest
	(*ListAmendmentsResponse)(nil), // 21: kyc.dsl.ListAmendmentsResponse
	(*AmendmentType)(nil),          // 22: kyc.dsl.AmendmentType
	(*GetGrammarRequest)(nil),      // 23: kyc.dsl.GetGrammarRequest
	(*GrammarResponse)(nil),        // 24: kyc.dsl.GrammarResponse
	nil,                            // 25: kyc.dsl.ExecuteRequest.ArgumentsEntry
	nil,                            // 26: kyc.dsl.AmendRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
}
var file_api_proto_dsl_service_proto_depIdxs = []int32{
	25, // 0: kyc.dsl.ExecuteRequest.arguments:type_name -> kyc.dsl.ExecuteRequest.ArgumentsEntry
	4,  // 1: kyc.dsl.ValidationResult.issues:type_name -> kyc.dsl.ValidationIssue
	7,  // 2: kyc.dsl.ParseResponse.cases:type_name -> kyc.dsl.ParsedCase
	8,  // 3: kyc.dsl.ParsedCase.ownership:type_name -> kyc.dsl.OwnershipStructure
	12, // 4: kyc.dsl.ParsedCase.data_dictionary:type_name -> kyc.dsl.DataDictionary
	14, // 5: kyc.dsl.ParsedCase.document_requirements:type_name -> kyc.dsl.DocumentRequirements
	9,  // 6: kyc.dsl.OwnershipStructure.owners:type_name -> kyc.dsl.Owner
	10, // 7: kyc.dsl.OwnershipStructure.beneficial_owners:type_name -> kyc.dsl.BeneficialOwner
	11, // 8: kyc.dsl.OwnershipStructure.controllers:type_name -> kyc.dsl.Controller
	13, // 9: kyc.dsl.DataDictionary.attributes:type_name -> kyc.dsl.AttributeDefinition
	15, // 10: kyc.dsl.DocumentRequirements.required:type_name -> kyc.dsl.DocumentRequirement
	7,  // 11: kyc.dsl.SerializeRequest.case:type_name -> kyc.dsl.ParsedCase
	26, // 12: kyc.dsl.AmendRequest.parameters:type_name -> kyc.dsl.AmendRequest.ParametersEntry
	22, // 13: kyc.dsl.ListAmendmentsResponse.amendments:type_name -> kyc.dsl.AmendmentType
	27, // 14: kyc.dsl.GrammarResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 15: kyc.dsl.DslService.Execute:input_type -> kyc.dsl.ExecuteRequest
	2,  // 16: kyc.dsl.DslService.Validate:input_type -> kyc.dsl.ValidateRequest
	5,  // 17: kyc.dsl.DslService.Parse:input_type -> kyc.dsl.ParseRequest
	16, // 18: kyc.dsl.DslService.Serialize:input_type -> kyc.dsl.SerializeRequest
	18, // 19: kyc.dsl.DslService.Amend:input_type -> kyc.dsl.AmendRequest
	20, // 20: kyc.dsl.DslService.ListAmendments:input_type -> kyc.dsl.ListAmendmentsRequest
	23, // 21: kyc.dsl.DslService.GetGrammar:input_type -> kyc.dsl.GetGrammarRequest
	1,  // 22: kyc.dsl.DslService.Execute:output_type -> kyc.dsl.ExecuteResponse
	3,  // 23: kyc.dsl.DslService.Validate:output_type -> kyc.dsl.ValidationResult
	6,  // 24: kyc.dsl.DslService.Parse:output_type -> kyc.dsl.ParseResponse
	17, // 25: kyc.dsl.DslService.Serialize:output_type -> kyc.dsl.SerializeResponse
	19, // 26: kyc.dsl.DslService.Amend:output_type -> kyc.dsl.AmendResponse
	21, // 27: kyc.dsl.DslService.ListAmendments:output_type -> kyc.dsl.ListAmendmentsResponse
	24, // 28: kyc.dsl.DslService.GetGrammar:output_type -> kyc.dsl.GrammarResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_dsl_service_proto_init() }
func file_api_proto_dsl_service_proto_init() {
	if File_api_proto_dsl_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dsl_service_proto_rawDesc), len(file_api_proto_dsl_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dsl_service_proto_goTypes,
		DependencyIndexes: file_api_proto_dsl_service_proto_depIdxs,
		MessageInfos:      file_api_proto_dsl_service_proto_msgTypes,
	}.Build()
	File_api_proto_dsl_service_proto = out.File
	file_api_proto_dsl_service_proto_goTypes = nil
	file_api_proto_dsl_service_proto_depIdxs = nil
}
