// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/rag_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RagSearchRequest contains parameters for semantic search
type RagSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchRequest) Reset() {
	*x = RagSearchRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchRequest) ProtoMessage() {}

func (x *RagSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchRequest.ProtoReflect.Descriptor instead.
func (*RagSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *RagSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RagSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// RagSearchResponse contains search results
type RagSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Results       []*RagResult           `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchResponse) Reset() {
	*x = RagSearchResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchResponse) ProtoMessage() {}

func (x *RagSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchResponse.ProtoReflect.Descriptor instead.
func (*RagSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *RagSearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RagSearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RagSearchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RagSearchResponse) GetResults() []*RagResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// RagResult represents a single search result
type RagResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttributeCode       string                 `protobuf:"bytes,1,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	RiskLevel           string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	DataType            string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Synonyms            []string               `protobuf:"bytes,5,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	RegulatoryCitations []string               `protobuf:"bytes,6,rep,name=regulatory_citations,json=regulatoryCitations,proto3" json:"regulatory_citations,omitempty"`
	ExampleValues       []string               `protobuf:"bytes,7,rep,name=example_values,json=exampleValues,proto3" json:"example_values,omitempty"`
	SimilarityScore     float32                `protobuf:"fixed32,8,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Distance            float32                `protobuf:"fixed32,9,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RagResult) Reset() {
	*x = RagResult{}
	mi := &file_api_proto_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagResult) ProtoMessage() {}

func (x *RagResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagResult.ProtoReflect.Descriptor instead.
func (*RagResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *RagResult) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

func (x *RagResult) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *RagResult) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RagResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RagResult) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *RagResult) GetRegulatoryCitations() []string {
	if x != nil {
		return x.RegulatoryCitations
	}
	return nil
}

func (x *RagResult) GetExampleValues() []string {
	if x != nil {
		return x.ExampleValues
	}
	return nil
}

func (x *RagResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *RagResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// SimilarAttributesRequest finds similar attributes to a source
type SimilarAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeCode string                 `protobuf:"bytes,1,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarAttributesRequest) Reset() {
	*x = SimilarAttributesRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarAttributesRequest) ProtoMessage() {}

func (x *SimilarAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarAttributesRequest.ProtoReflect.Descriptor instead.
func (*SimilarAttributesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *SimilarAttributesRequest) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

func (x *SimilarAttributesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// TextSearchRequest performs text-based search
type TextSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSearchRequest) Reset() {
	*x = TextSearchRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchRequest) ProtoMessage() {}

func (x *TextSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchRequest.ProtoReflect.Descriptor instead.
func (*TextSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *TextSearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *TextSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetAttributeRequest retrieves a specific attribute
type GetAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeCode string                 `protobuf:"bytes,1,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeRequest) Reset() {
	*x = GetAttributeRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeRequest) ProtoMessage() {}

func (x *GetAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttributeRequest) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

// AttributeMetadata contains complete attribute information
type AttributeMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Code                string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	RiskLevel           string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	DataType            string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Synonyms            []string               `protobuf:"bytes,5,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	BusinessContext     string                 `protobuf:"bytes,6,opt,name=business_context,json=businessContext,proto3" json:"business_context,omitempty"`
	RegulatoryCitations []string               `protobuf:"bytes,7,rep,name=regulatory_citations,json=regulatoryCitations,proto3" json:"regulatory_citations,omitempty"`
	ComplianceNotes     []string               `protobuf:"bytes,8,rep,name=compliance_notes,json=complianceNotes,proto3" json:"compliance_notes,omitempty"`
	ExampleValues       []string               `protobuf:"bytes,9,rep,name=example_values,json=exampleValues,proto3" json:"example_values,omitempty"`
	ValidationRules     string                 `protobuf:"bytes,10,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HasEmbedding        bool                   `protobuf:"varint,13,opt,name=has_embedding,json=hasEmbedding,proto3" json:"has_embedding,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttributeMetadata) Reset() {
	*x = AttributeMetadata{}
	mi := &file_api_proto_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeMetadata) ProtoMessage() {}

func (x *AttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeMetadata.ProtoReflect.Descriptor instead.
func (*AttributeMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{6}
}

func (x *AttributeMetadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AttributeMetadata) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AttributeMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttributeMetadata) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *AttributeMetadata) GetBusinessContext() string {
	if x != nil {
		return x.BusinessContext
	}
	return ""
}

func (x *AttributeMetadata) GetRegulatoryCitations() []string {
	if x != nil {
		return x.RegulatoryCitations
	}
	return nil
}

func (x *AttributeMetadata) GetComplianceNotes() []string {
	if x != nil {
		return x.ComplianceNotes
	}
	return nil
}

func (x *AttributeMetadata) GetExampleValues() []string {
	if x != nil {
		return x.ExampleValues
	}
	return nil
}

func (x *AttributeMetadata) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

func (x *AttributeMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AttributeMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AttributeMetadata) GetHasEmbedding() bool {
	if x != nil {
		return x.HasEmbedding
	}
	return false
}

// RagFeedbackRequest submits feedback on search results
type RagFeedbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryText      string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	AttributeCode  string                 `protobuf:"bytes,2,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	DocumentCode   string                 `protobuf:"bytes,3,opt,name=document_code,json=documentCode,proto3" json:"document_code,omitempty"`
	RegulationCode string                 `protobuf:"bytes,4,opt,name=regulation_code,json=regulationCode,proto3" json:"regulation_code,omitempty"`
	Feedback       string                 `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`       // positive, negative, neutral
	Confidence     float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0-1.0
	AgentName      string                 `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType      string                 `protobuf:"bytes,8,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // human, ai, automated
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RagFeedbackRequest) Reset() {
	*x = RagFeedbackRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagFeedbackRequest) ProtoMessage() {}

func (x *RagFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagFeedbackRequest.ProtoReflect.Descriptor instead.
func (*RagFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{7}
}

func (x *RagFeedbackRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RagFeedbackRequest) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

func (x *RagFeedbackRequest) GetDocumentCode() string {
	if x != nil {
		return x.DocumentCode
	}
	return ""
}

func (x *RagFeedbackRequest) GetRegulationCode() string {
	if x != nil {
		return x.RegulationCode
	}
	return ""
}

func (x *RagFeedbackRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *RagFeedbackRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RagFeedbackRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RagFeedbackRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// RagFeedbackResponse confirms feedback submission
type RagFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	AgentName     string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagFeedbackResponse) Reset() {
	*x = RagFeedbackResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagFeedbackResponse) ProtoMessage() {}

func (x *RagFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagFeedbackResponse.ProtoReflect.Descriptor instead.
func (*RagFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{8}
}

func (x *RagFeedbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RagFeedbackResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RagFeedbackResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *RagFeedbackResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RagFeedbackResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetRecentFeedbackRequest retrieves recent feedback
type GetRecentFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentFeedbackRequest) Reset() {
	*x = GetRecentFeedbackRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentFeedbackRequest) ProtoMessage() {}

func (x *GetRecentFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetRecentFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecentFeedbackRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// RagFeedback represents a feedback entry
type RagFeedback struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QueryText      string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	AttributeCode  string                 `protobuf:"bytes,3,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	DocumentCode   string                 `protobuf:"bytes,4,opt,name=document_code,json=documentCode,proto3" json:"document_code,omitempty"`
	RegulationCode string                 `protobuf:"bytes,5,opt,name=regulation_code,json=regulationCode,proto3" json:"regulation_code,omitempty"`
	Feedback       string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Confidence     float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AgentName      string                 `protobuf:"bytes,8,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType      string                 `protobuf:"bytes,9,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RagFeedback) Reset() {
	*x = RagFeedback{}
	mi := &file_api_proto_rag_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagFeedback) ProtoMessage() {}

func (x *RagFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagFeedback.ProtoReflect.Descriptor instead.
func (*RagFeedback) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{10}
}

func (x *RagFeedback) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RagFeedback) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RagFeedback) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

func (x *RagFeedback) GetDocumentCode() string {
	if x != nil {
		return x.DocumentCode
	}
	return ""
}

func (x *RagFeedback) GetRegulationCode() string {
	if x != nil {
		return x.RegulationCode
	}
	return ""
}

func (x *RagFeedback) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *RagFeedback) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RagFeedback) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RagFeedback) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RagFeedback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetFeedbackAnalyticsRequest retrieves analytics
type GetFeedbackAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           int32                  `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"` // Top N attributes to include
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackAnalyticsRequest) Reset() {
	*x = GetFeedbackAnalyticsRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackAnalyticsRequest) ProtoMessage() {}

func (x *GetFeedbackAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFeedbackAnalyticsRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

// FeedbackAnalytics contains comprehensive feedback statistics
type FeedbackAnalytics struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	TotalFeedback  int32                       `protobuf:"varint,1,opt,name=total_feedback,json=totalFeedback,proto3" json:"total_feedback,omitempty"`
	PositiveCount  int32                       `protobuf:"varint,2,opt,name=positive_count,json=positiveCount,proto3" json:"positive_count,omitempty"`
	NegativeCount  int32                       `protobuf:"varint,3,opt,name=negative_count,json=negativeCount,proto3" json:"negative_count,omitempty"`
	NeutralCount   int32                       `protobuf:"varint,4,opt,name=neutral_count,json=neutralCount,proto3" json:"neutral_count,omitempty"`
	AvgConfidence  float32                     `protobuf:"fixed32,5,opt,name=avg_confidence,json=avgConfidence,proto3" json:"avg_confidence,omitempty"`
	ByAgentType    map[string]int32            `protobuf:"bytes,6,rep,name=by_agent_type,json=byAgentType,proto3" json:"by_agent_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopAttributes  []*AttributeFeedbackSummary `protobuf:"bytes,7,rep,name=top_attributes,json=topAttributes,proto3" json:"top_attributes,omitempty"`
	RecentFeedback []*RagFeedback              `protobuf:"bytes,8,rep,name=recent_feedback,json=recentFeedback,proto3" json:"recent_feedback,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeedbackAnalytics) Reset() {
	*x = FeedbackAnalytics{}
	mi := &file_api_proto_rag_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackAnalytics) ProtoMessage() {}

func (x *FeedbackAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackAnalytics.ProtoReflect.Descriptor instead.
func (*FeedbackAnalytics) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{12}
}

func (x *FeedbackAnalytics) GetTotalFeedback() int32 {
	if x != nil {
		return x.TotalFeedback
	}
	return 0
}

func (x *FeedbackAnalytics) GetPositiveCount() int32 {
	if x != nil {
		return x.PositiveCount
	}
	return 0
}

func (x *FeedbackAnalytics) GetNegativeCount() int32 {
	if x != nil {
		return x.NegativeCount
	}
	return 0
}

func (x *FeedbackAnalytics) GetNeutralCount() int32 {
	if x != nil {
		return x.NeutralCount
	}
	return 0
}

func (x *FeedbackAnalytics) GetAvgConfidence() float32 {
	if x != nil {
		return x.AvgConfidence
	}
	return 0
}

func (x *FeedbackAnalytics) GetByAgentType() map[string]int32 {
	if x != nil {
		return x.ByAgentType
	}
	return nil
}

func (x *FeedbackAnalytics) GetTopAttributes() []*AttributeFeedbackSummary {
	if x != nil {
		return x.TopAttributes
	}
	return nil
}

func (x *FeedbackAnalytics) GetRecentFeedback() []*RagFeedback {
	if x != nil {
		return x.RecentFeedback
	}
	return nil
}

// AttributeFeedbackSummary represents per-attribute feedback stats
type AttributeFeedbackSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeCode string                 `protobuf:"bytes,1,opt,name=attribute_code,json=attributeCode,proto3" json:"attribute_code,omitempty"`
	Feedback      string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	FeedbackCount int32                  `protobuf:"varint,3,opt,name=feedback_count,json=feedbackCount,proto3" json:"feedback_count,omitempty"`
	AvgConfidence float32                `protobuf:"fixed32,4,opt,name=avg_confidence,json=avgConfidence,proto3" json:"avg_confidence,omitempty"`
	AgentTypes    string                 `protobuf:"bytes,5,opt,name=agent_types,json=agentTypes,proto3" json:"agent_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeFeedbackSummary) Reset() {
	*x = AttributeFeedbackSummary{}
	mi := &file_api_proto_rag_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeFeedbackSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeFeedbackSummary) ProtoMessage() {}

func (x *AttributeFeedbackSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeFeedbackSummary.ProtoReflect.Descriptor instead.
func (*AttributeFeedbackSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{13}
}

func (x *AttributeFeedbackSummary) GetAttributeCode() string {
	if x != nil {
		return x.AttributeCode
	}
	return ""
}

func (x *AttributeFeedbackSummary) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *AttributeFeedbackSummary) GetFeedbackCount() int32 {
	if x != nil {
		return x.FeedbackCount
	}
	return 0
}

func (x *AttributeFeedbackSummary) GetAvgConfidence() float32 {
	if x != nil {
		return x.AvgConfidence
	}
	return 0
}

func (x *AttributeFeedbackSummary) GetAgentTypes() string {
	if x != nil {
		return x.AgentTypes
	}
	return ""
}

// GetMetadataStatsRequest retrieves repository stats
type GetMetadataStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataStatsRequest) Reset() {
	*x = GetMetadataStatsRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataStatsRequest) ProtoMessage() {}

func (x *GetMetadataStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{14}
}

// MetadataStats contains repository statistics
type MetadataStats struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TotalAttributes          int32                  `protobuf:"varint,1,opt,name=total_attributes,json=totalAttributes,proto3" json:"total_attributes,omitempty"`
	AttributesWithEmbeddings int32                  `protobuf:"varint,2,opt,name=attributes_with_embeddings,json=attributesWithEmbeddings,proto3" json:"attributes_with_embeddings,omitempty"`
	EmbeddingCoveragePercent float32                `protobuf:"fixed32,3,opt,name=embedding_coverage_percent,json=embeddingCoveragePercent,proto3" json:"embedding_coverage_percent,omitempty"`
	RiskDistribution         []*RiskDistribution    `protobuf:"bytes,4,rep,name=risk_distribution,json=riskDistribution,proto3" json:"risk_distribution,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MetadataStats) Reset() {
	*x = MetadataStats{}
	mi := &file_api_proto_rag_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataStats) ProtoMessage() {}

func (x *MetadataStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataStats.ProtoReflect.Descriptor instead.
func (*MetadataStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{15}
}

func (x *MetadataStats) GetTotalAttributes() int32 {
	if x != nil {
		return x.TotalAttributes
	}
	return 0
}

func (x *MetadataStats) GetAttributesWithEmbeddings() int32 {
	if x != nil {
		return x.AttributesWithEmbeddings
	}
	return 0
}

func (x *MetadataStats) GetEmbeddingCoveragePercent() float32 {
	if x != nil {
		return x.EmbeddingCoveragePercent
	}
	return 0
}

func (x *MetadataStats) GetRiskDistribution() []*RiskDistribution {
	if x != nil {
		return x.RiskDistribution
	}
	return nil
}

// RiskDistribution represents count by risk level
type RiskDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiskLevel     string                 `protobuf:"bytes,1,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskDistribution) Reset() {
	*x = RiskDistribution{}
	mi := &file_api_proto_rag_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskDistribution) ProtoMessage() {}

func (x *RiskDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskDistribution.ProtoReflect.Descriptor instead.
func (*RiskDistribution) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{16}
}

func (x *RiskDistribution) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *RiskDistribution) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// EnrichedSearchResponse contains results with full context
type EnrichedSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Results       []*EnrichedResult      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedSearchResponse) Reset() {
	*x = EnrichedSearchResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedSearchResponse) ProtoMessage() {}

func (x *EnrichedSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedSearchResponse.ProtoReflect.Descriptor instead.
func (*EnrichedSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{17}
}

func (x *EnrichedSearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EnrichedSearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnrichedSearchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EnrichedSearchResponse) GetResults() []*EnrichedResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// EnrichedResult contains attribute with related docs and regulations
type EnrichedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *RagResult             `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Documents     []*DocumentInfo        `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	Regulations   []*RegulationInfo      `protobuf:"bytes,3,rep,name=regulations,proto3" json:"regulations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedResult) Reset() {
	*x = EnrichedResult{}
	mi := &file_api_proto_rag_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedResult) ProtoMessage() {}

func (x *EnrichedResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedResult.ProtoReflect.Descriptor instead.
func (*EnrichedResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{18}
}

func (x *EnrichedResult) GetAttribute() *RagResult {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *EnrichedResult) GetDocuments() []*DocumentInfo {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *EnrichedResult) GetRegulations() []*RegulationInfo {
	if x != nil {
		return x.Regulations
	}
	return nil
}

// DocumentInfo represents document metadata
type DocumentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Jurisdiction  string                 `protobuf:"bytes,3,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	DocType       string                 `protobuf:"bytes,4,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentInfo) Reset() {
	*x = DocumentInfo{}
	mi := &file_api_proto_rag_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInfo) ProtoMessage() {}

func (x *DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInfo.ProtoReflect.Descriptor instead.
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{19}
}

func (x *DocumentInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DocumentInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentInfo) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *DocumentInfo) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *DocumentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// RegulationInfo represents regulation metadata
type RegulationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Citation      string                 `protobuf:"bytes,3,opt,name=citation,proto3" json:"citation,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegulationInfo) Reset() {
	*x = RegulationInfo{}
	mi := &file_api_proto_rag_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegulationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegulationInfo) ProtoMessage() {}

func (x *RegulationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegulationInfo.ProtoReflect.Descriptor instead.
func (*RegulationInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{20}
}

func (x *RegulationInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegulationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegulationInfo) GetCitation() string {
	if x != nil {
		return x.Citation
	}
	return ""
}

func (x *RegulationInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RegulationInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// HealthCheckRequest checks system health
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{21}
}

// HealthCheckResponse contains health status
type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Dimensions     int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DatabaseStatus string                 `protobuf:"bytes,5,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"`
	EmbedderStatus string                 `protobuf:"bytes,6,opt,name=embedder_status,json=embedderStatus,proto3" json:"embedder_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{22}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HealthCheckResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDatabaseStatus() string {
	if x != nil {
		return x.DatabaseStatus
	}
	return ""
}

func (x *HealthCheckResponse) GetEmbedderStatus() string {
	if x != nil {
		return x.EmbedderStatus
	}
	return ""
}

var File_api_proto_rag_service_proto protoreflect.FileDescriptor

const file_api_proto_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/rag_service.proto\x12\akyc.rag\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x10RagSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x11RagSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12,\n" +
	"\aresults\x18\x04 \x03(\v2\x12.kyc.rag.RagResultR\aresults\"\xcd\x02\n" +
	"\tRagResult\x12%\n" +
	"\x0eattribute_code\x18\x01 \x01(\tR\rattributeCode\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsynonyms\x18\x05 \x03(\tR\bsynonyms\x121\n" +
	"\x14regulatory_citations\x18\x06 \x03(\tR\x13regulatoryCitations\x12%\n" +
	"\x0eexample_values\x18\a \x03(\tR\rexampleValues\x12)\n" +
	"\x10similarity_score\x18\b \x01(\x02R\x0fsimilarityScore\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x02R\bdistance\"W\n" +
	"\x18SimilarAttributesRequest\x12%\n" +
	"\x0eattribute_code\x18\x01 \x01(\tR\rattributeCode\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x11TextSearchRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"<\n" +
	"\x13GetAttributeRequest\x12%\n" +
	"\x0eattribute_code\x18\x01 \x01(\tR\rattributeCode\"\x97\x04\n" +
	"\x11AttributeMetadata\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsynonyms\x18\x05 \x03(\tR\bsynonyms\x12)\n" +
	"\x10business_context\x18\x06 \x01(\tR\x0fbusinessContext\x121\n" +
	"\x14regulatory_citations\x18\a \x03(\tR\x13regulatoryCitations\x12)\n" +
	"\x10compliance_notes\x18\b \x03(\tR\x0fcomplianceNotes\x12%\n" +
	"\x0eexample_values\x18\t \x03(\tR\rexampleValues\x12)\n" +
	"\x10validation_rules\x18\n" +
	" \x01(\tR\x0fvalidationRules\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rhas_embedding\x18\r \x01(\bR\fhasEmbedding\"\xa2\x02\n" +
	"\x12RagFeedbackRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12%\n" +
	"\x0eattribute_code\x18\x02 \x01(\tR\rattributeCode\x12#\n" +
	"\rdocument_code\x18\x03 \x01(\tR\fdocumentCode\x12'\n" +
	"\x0fregulation_code\x18\x04 \x01(\tR\x0eregulationCode\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"agent_type\x18\b \x01(\tR\tagentType\"\xb3\x01\n" +
	"\x13RagFeedbackResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\x18GetRecentFeedbackRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xe6\x02\n" +
	"\vRagFeedback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12%\n" +
	"\x0eattribute_code\x18\x03 \x01(\tR\rattributeCode\x12#\n" +
	"\rdocument_code\x18\x04 \x01(\tR\fdocumentCode\x12'\n" +
	"\x0fregulation_code\x18\x05 \x01(\tR\x0eregulationCode\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedback\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"agent_name\x18\b \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"agent_type\x18\t \x01(\tR\tagentType\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x1bGetFeedbackAnalyticsRequest\x12\x10\n" +
	"\x03top\x18\x01 \x01(\x05R\x03top\"\xee\x03\n" +
	"\x11FeedbackAnalytics\x12%\n" +
	"\x0etotal_feedback\x18\x01 \x01(\x05R\rtotalFeedback\x12%\n" +
	"\x0epositive_count\x18\x02 \x01(\x05R\rpositiveCount\x12%\n" +
	"\x0enegative_count\x18\x03 \x01(\x05R\rnegativeCount\x12#\n" +
	"\rneutral_count\x18\x04 \x01(\x05R\fneutralCount\x12%\n" +
	"\x0eavg_confidence\x18\x05 \x01(\x02R\ravgConfidence\x12O\n" +
	"\rby_agent_type\x18\x06 \x03(\v2+.kyc.rag.FeedbackAnalytics.ByAgentTypeEntryR\vbyAgentType\x12H\n" +
	"\x0etop_attributes\x18\a \x03(\v2!.kyc.rag.AttributeFeedbackSummaryR\rtopAttributes\x12=\n" +
	"\x0frecent_feedback\x18\b \x03(\v2\x14.kyc.rag.RagFeedbackR\x0erecentFeedback\x1a>\n" +
	"\x10ByAgentTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xcc\x01\n" +
	"\x18AttributeFeedbackSummary\x12%\n" +
	"\x0eattribute_code\x18\x01 \x01(\tR\rattributeCode\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12%\n" +
	"\x0efeedback_count\x18\x03 \x01(\x05R\rfeedbackCount\x12%\n" +
	"\x0eavg_confidence\x18\x04 \x01(\x02R\ravgConfidence\x12\x1f\n" +
	"\vagent_types\x18\x05 \x01(\tR\n" +
	"agentTypes\"\x19\n" +
	"\x17GetMetadataStatsRequest\"\xfe\x01\n" +
	"\rMetadataStats\x12)\n" +
	"\x10total_attributes\x18\x01 \x01(\x05R\x0ftotalAttributes\x12<\n" +
	"\x1aattributes_with_embeddings\x18\x02 \x01(\x05R\x18attributesWithEmbeddings\x12<\n" +
	"\x1aembedding_coverage_percent\x18\x03 \x01(\x02R\x18embeddingCoveragePercent\x12F\n" +
	"\x11risk_distribution\x18\x04 \x03(\v2\x19.kyc.rag.RiskDistributionR\x10riskDistribution\"G\n" +
	"\x10RiskDistribution\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x01 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8d\x01\n" +
	"\x16EnrichedSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x121\n" +
	"\aresults\x18\x04 \x03(\v2\x17.kyc.rag.EnrichedResultR\aresults\"\xb2\x01\n" +
	"\x0eEnrichedResult\x120\n" +
	"\tattribute\x18\x01 \x01(\v2\x12.kyc.rag.RagResultR\tattribute\x123\n" +
	"\tdocuments\x18\x02 \x03(\v2\x15.kyc.rag.DocumentInfoR\tdocuments\x129\n" +
	"\vregulations\x18\x03 \x03(\v2\x17.kyc.rag.RegulationInfoR\vregulations\"\x99\x01\n" +
	"\fDocumentInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\"\n" +
	"\fjurisdiction\x18\x03 \x01(\tR\fjurisdiction\x12\x19\n" +
	"\bdoc_type\x18\x04 \x01(\tR\adocType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x88\x01\n" +
	"\x0eRegulationInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcitation\x18\x03 \x01(\tR\bcitation\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"\x14\n" +
	"\x12HealthCheckRequest\"\xef\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fdatabase_status\x18\x05 \x01(\tR\x0edatabaseStatus\x12'\n" +
	"\x0fembedder_status\x18\x06 \x01(\tR\x0eembedderStatus2\xa0\x06\n" +
	"\n" +
	"RagService\x12H\n" +
	"\x0fAttributeSearch\x12\x19.kyc.rag.RagSearchRequest\x1a\x1a.kyc.rag.RagSearchResponse\x12R\n" +
	"\x11SimilarAttributes\x12!.kyc.rag.SimilarAttributesRequest\x1a\x1a.kyc.rag.RagSearchResponse\x12D\n" +
	"\n" +
	"TextSearch\x12\x1a.kyc.rag.TextSearchRequest\x1a\x1a.kyc.rag.RagSearchResponse\x12H\n" +
	"\fGetAttribute\x12\x1c.kyc.rag.GetAttributeRequest\x1a\x1a.kyc.rag.AttributeMetadata\x12K\n" +
	"\x0eSubmitFeedback\x12\x1b.kyc.rag.RagFeedbackRequest\x1a\x1c.kyc.rag.RagFeedbackResponse\x12N\n" +
	"\x11GetRecentFeedback\x12!.kyc.rag.GetRecentFeedbackRequest\x1a\x14.kyc.rag.RagFeedback0\x01\x12X\n" +
	"\x14GetFeedbackAnalytics\x12$.kyc.rag.GetFeedbackAnalyticsRequest\x1a\x1a.kyc.rag.FeedbackAnalytics\x12L\n" +
	"\x10GetMetadataStats\x12 .kyc.rag.GetMetadataStatsRequest\x1a\x16.kyc.rag.MetadataStats\x12U\n" +
	"\x17EnrichedAttributeSearch\x12\x19.kyc.rag.RagSearchRequest\x1a\x1f.kyc.rag.EnrichedSearchResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.kyc.rag.HealthCheckRequest\x1a\x1c.kyc.rag.HealthCheckResponseB(Z&github.com/adamtc007/KYC-DSL/api/pb;pbb\x06proto3"

var (
	file_api_proto_rag_service_proto_rawDescOnce sync.Once
	file_api_proto_rag_service_proto_rawDescData []byte
)

func file_api_proto_rag_service_proto_rawDescGZIP() []byte {
	file_api_proto_rag_service_proto_rawDescOnce.Do(func() {
		file_api_proto_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rag_service_proto_rawDesc), len(file_api_proto_rag_service_proto_rawDesc)))
	})
	return file_api_proto_rag_service_proto_rawDescData
}

var file_api_proto_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_rag_service_proto_goTypes = []any{
	(*RagSearchRequest)(nil),            // 0: kyc.rag.RagSearchRequest
	(*RagSearchResponse)(nil),           // 1: kyc.rag.RagSearchResponse
	(*RagResult)(nil),                   // 2: kyc.rag.RagResult
	(*SimilarAttributesRequest)(nil),    // 3: kyc.rag.SimilarAttributesRequest
	(*TextSearchRequest)(nil),           // 4: kyc.rag.TextSearchRequest
	(*GetAttributeRequest)(nil),         // 5: kyc.rag.GetAttributeRequest
	(*AttributeMetadata)(nil),           // 6: kyc.rag.AttributeMetadata
	(*RagFeedbackRequest)(nil),          // 7: kyc.rag.RagFeedbackRequest
	(*RagFeedbackResponse)(nil),         // 8: kyc.rag.RagFeedbackResponse
	(*GetRecentFeedbackRequest)(nil),    // 9: kyc.rag.GetRecentFeedbackRequest
	(*RagFeedback)(nil),                 // 10: kyc.rag.RagFeedback
	(*GetFeedbackAnalyticsRequest)(nil), // 11: kyc.rag.GetFeedbackAnalyticsRequest
	(*FeedbackAnalytics)(nil),           // 12: kyc.rag.FeedbackAnalytics
	(*AttributeFeedbackSummary)(nil),    // 13: kyc.rag.AttributeFeedbackSummary
	(*GetMetadataStatsRequest)(nil),     // 14: kyc.rag.GetMetadataStatsRequest
	(*MetadataStats)(nil),               // 15: kyc.rag.MetadataStats
	(*RiskDistribution)(nil),            // 16: kyc.rag.RiskDistribution
	(*EnrichedSearchResponse)(nil),      // 17: kyc.rag.EnrichedSearchResponse
	(*EnrichedResult)(nil),              // 18: kyc.rag.EnrichedResult
	(*DocumentInfo)(nil),                // 19: kyc.rag.DocumentInfo
	(*RegulationInfo)(nil),              // 20: kyc.rag.RegulationInfo
	(*HealthCheckRequest)(nil),          // 21: kyc.rag.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 22: kyc.rag.HealthCheckResponse
	nil,                                 // 23: kyc.rag.FeedbackAnalytics.ByAgentTypeEntry
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
}
var file_api_proto_rag_service_proto_depIdxs = []int32{
	2,  // 0: kyc.rag.RagSearchResponse.results:type_name -> kyc.rag.RagResult
	24, // 1: kyc.rag.AttributeMetadata.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: kyc.rag.AttributeMetadata.updated_at:type_name -> google.protobuf.Timestamp
	24, // 3: kyc.rag.RagFeedbackResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: kyc.rag.RagFeedback.created_at:type_name -> google.protobuf.Timestamp
	23, // 5: kyc.rag.FeedbackAnalytics.by_agent_type:type_name -> kyc.rag.FeedbackAnalytics.ByAgentTypeEntry
	13, // 6: kyc.rag.FeedbackAnalytics.top_attributes:type_name -> kyc.rag.AttributeFeedbackSummary
	10, // 7: kyc.rag.FeedbackAnalytics.recent_feedback:type_name -> kyc.rag.RagFeedback
	16, // 8: kyc.rag.MetadataStats.risk_distribution:type_name -> kyc.rag.RiskDistribution
	18, // 9: kyc.rag.EnrichedSearchResponse.results:type_name -> kyc.rag.EnrichedResult
	2,  // 10: kyc.rag.EnrichedResult.attribute:type_name -> kyc.rag.RagResult
	19, // 11: kyc.rag.EnrichedResult.documents:type_name -> kyc.rag.DocumentInfo
	20, // 12: kyc.rag.EnrichedResult.regulations:type_name -> kyc.rag.RegulationInfo
	24, // 13: kyc.rag.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 14: kyc.rag.RagService.AttributeSearch:input_type -> kyc.rag.RagSearchRequest
	3,  // 15: kyc.rag.RagService.SimilarAttributes:input_type -> kyc.rag.SimilarAttributesRequest
	4,  // 16: kyc.rag.RagService.TextSearch:input_type -> kyc.rag.TextSearchRequest
	5,  // 17: kyc.rag.RagService.GetAttribute:input_type -> kyc.rag.GetAttributeRequest
	7,  // 18: kyc.rag.RagService.SubmitFeedback:input_type -> kyc.rag.RagFeedbackRequest
	9,  // 19: kyc.rag.RagService.GetRecentFeedback:input_type -> kyc.rag.GetRecentFeedbackRequest
	11, // 20: kyc.rag.RagService.GetFeedbackAnalytics:input_type -> kyc.rag.GetFeedbackAnalyticsRequest
	14, // 21: kyc.rag.RagService.GetMetadataStats:input_type -> kyc.rag.GetMetadataStatsRequest
	0,  // 22: kyc.rag.RagService.EnrichedAttributeSearch:input_type -> kyc.rag.RagSearchRequest
	21, // 23: kyc.rag.RagService.HealthCheck:input_type -> kyc.rag.HealthCheckRequest
	1,  // 24: kyc.rag.RagService.AttributeSearch:output_type -> kyc.rag.RagSearchResponse
	1,  // 25: kyc.rag.RagService.SimilarAttributes:output_type -> kyc.rag.RagSearchResponse
	1,  // 26: kyc.rag.RagService.TextSearch:output_type -> kyc.rag.RagSearchResponse
	6,  // 27: kyc.rag.RagService.GetAttribute:output_type -> kyc.rag.AttributeMetadata
	8,  // 28: kyc.rag.RagService.SubmitFeedback:output_type -> kyc.rag.RagFeedbackResponse
	10, // 29: kyc.rag.RagService.GetRecentFeedback:output_type -> kyc.rag.RagFeedback
	12, // 30: kyc.rag.RagService.GetFeedbackAnalytics:output_type -> kyc.rag.FeedbackAnalytics
	15, // 31: kyc.rag.RagService.GetMetadataStats:output_type -> kyc.rag.MetadataStats
	17, // 32: kyc.rag.RagService.EnrichedAttributeSearch:output_type -> kyc.rag.EnrichedSearchResponse
	22, // 33: kyc.rag.RagService.HealthCheck:output_type -> kyc.rag.HealthCheckResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_rag_service_proto_init() }
func file_api_proto_rag_service_proto_init() {
	if File_api_proto_rag_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rag_service_proto_rawDesc), len(file_api_proto_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rag_service_proto_goTypes,
		DependencyIndexes: file_api_proto_rag_service_proto_depIdxs,
		MessageInfos:      file_api_proto_rag_service_proto_msgTypes,
	}.Build()
	File_api_proto_rag_service_proto = out.File
	file_api_proto_rag_service_proto_goTypes = nil
	file_api_proto_rag_service_proto_depIdxs = nil
}
